
= Music trivia
:toc2:
:toclevels: 2
:toc-title: Welcome to Quarantine Music Trivia!

[subs=""]
++++++++++++
<style>
html, body { height: 100%; }
.fullheight { overflow-y:auto; height:100vh; }​
a { color:blue; }
a:visited { color:blue; }
a:active { color:blue; }
a[tabindex]:focus { color:blue; outline:none; }
</style>
++++++++++++

== Welcome
    

[[s0]]
== General (Q1--10)

[[s-General-Q1-10-q-1]]
=== Q1

[big]#General (Q1--10): Question 1#

==== Question

Name the performer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Moondance-2013-Remaster-7kfYOGndVfU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_0" onclick="toggle_hidden_q0_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_0]]
Van Morrison +
Moondance - 2013 Remaster / Van Morrison / Moondance (Deluxe Edition)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_0");
z.style.display = "none"
function toggle_hidden_q0_0() {
  var x = document.getElementById("answer_q0_0");
  var b = document.getElementById("button_q0_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-2, Next question -- Q2>>

[[s-General-Q1-10-q-2]]
=== Q2

[big]#General (Q1--10): Question 2#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Daft-Punk-Get-Lucky-Official-Audio-ft.-Pharrell-Williams-Nile-Rodgers-5NV6Rdv1a3I.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_1" onclick="toggle_hidden_q0_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_1]]
Get Lucky +
Get Lucky (feat. Pharrell Williams & Nile Rodgers) - Radio Edit / Daft Punk, Pharrell Williams, Nile Rodgers / Get Lucky (feat. Pharrell Williams & Nile Rodgers) [Radio Edit]


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_1");
z.style.display = "none"
function toggle_hidden_q0_1() {
  var x = document.getElementById("answer_q0_1");
  var b = document.getElementById("button_q0_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-1, Previous question -- Q1>> +
<<s-General-Q1-10-q-3, Next question -- Q3>>

[[s-General-Q1-10-q-3]]
=== Q3

[big]#General (Q1--10): Question 3#

==== Question

Name the song (title must be exact).


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Simon-Garfunkel-Bridge-Over-Troubled-Water-Audio-4G-YQA-bsOU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_2" onclick="toggle_hidden_q0_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_2]]
Bridge Over Troubled Water +
Bridge Over Troubled Water / Simon & Garfunkel / Bridge Over Troubled Water


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_2");
z.style.display = "none"
function toggle_hidden_q0_2() {
  var x = document.getElementById("answer_q0_2");
  var b = document.getElementById("button_q0_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-2, Previous question -- Q2>> +
<<s-General-Q1-10-q-4, Next question -- Q4>>

[[s-General-Q1-10-q-4]]
=== Q4

[big]#General (Q1--10): Question 4#

==== Question

Name the group.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/One-Way-Or-Another-Remastered-Fnb1xYDViDs.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_3" onclick="toggle_hidden_q0_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_3]]
Blondie +
One Way Or Another - Remastered / Blondie / One Way Or Another


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_3");
z.style.display = "none"
function toggle_hidden_q0_3() {
  var x = document.getElementById("answer_q0_3");
  var b = document.getElementById("button_q0_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-3, Previous question -- Q3>> +
<<s-General-Q1-10-q-5, Next question -- Q5>>

[[s-General-Q1-10-q-5]]
=== Q5

[big]#General (Q1--10): Question 5#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Twist-And-Shout-Remastered-2009-2RicaUqd9Hg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_4" onclick="toggle_hidden_q0_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_4]]
Twist and Shout +
Twist And Shout - Remastered 2009 / The Beatles / Please Please Me (Remastered)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_4");
z.style.display = "none"
function toggle_hidden_q0_4() {
  var x = document.getElementById("answer_q0_4");
  var b = document.getElementById("button_q0_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-4, Previous question -- Q4>> +
<<s-General-Q1-10-q-6, Next question -- Q6>>

[[s-General-Q1-10-q-6]]
=== Q6

[big]#General (Q1--10): Question 6#

==== Question

Name the song. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Jimmy-Buffett-Margaritaville-with-lyrics-ue2-ZVxpVjc.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_5" onclick="toggle_hidden_q0_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_5]]
Margaritaville +
Margaritaville / Jimmy Buffett / Songs You Know By Heart


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_5");
z.style.display = "none"
function toggle_hidden_q0_5() {
  var x = document.getElementById("answer_q0_5");
  var b = document.getElementById("button_q0_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-5, Previous question -- Q5>> +
<<s-General-Q1-10-q-7, Next question -- Q7>>

[[s-General-Q1-10-q-7]]
=== Q7

[big]#General (Q1--10): Question 7#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Free-Bird-CqnU-sJ8V-E.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_6" onclick="toggle_hidden_q0_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_6]]
Free Bird +
Free Bird / Lynyrd Skynyrd / Pronounced' Leh-'Nerd 'Skin-'Nerd


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_6");
z.style.display = "none"
function toggle_hidden_q0_6() {
  var x = document.getElementById("answer_q0_6");
  var b = document.getElementById("button_q0_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-6, Previous question -- Q6>> +
<<s-General-Q1-10-q-8, Next question -- Q8>>

[[s-General-Q1-10-q-8]]
=== Q8

[big]#General (Q1--10): Question 8#

==== Question

Name the song. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Blackbird-Remastered-2009-Man4Xw8Xypo.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_7" onclick="toggle_hidden_q0_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_7]]
Blackbird +
Blackbird - Remastered / The Beatles / The Beatles (Remastered)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_7");
z.style.display = "none"
function toggle_hidden_q0_7() {
  var x = document.getElementById("answer_q0_7");
  var b = document.getElementById("button_q0_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-7, Previous question -- Q7>> +
<<s-General-Q1-10-q-9, Next question -- Q9>>

[[s-General-Q1-10-q-9]]
=== Q9

[big]#General (Q1--10): Question 9#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Come-On-Eileen-GbpnAGajyMc.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_8" onclick="toggle_hidden_q0_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_8]]
Dexys Midnight Runners +
Come On Eileen / Dexys Midnight Runners / Too Rye Ay


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_8");
z.style.display = "none"
function toggle_hidden_q0_8() {
  var x = document.getElementById("answer_q0_8");
  var b = document.getElementById("button_q0_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-8, Previous question -- Q8>> +
<<s-General-Q1-10-q-10, Next question -- Q10>>

[[s-General-Q1-10-q-10]]
=== Q10

[big]#General (Q1--10): Question 10#

==== Question

Name the song.   


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Rebel-Rebel-1997-Remaster-Wb3bfsuttdk.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_9" onclick="toggle_hidden_q0_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_9]]
Rebel Rebel +
Rebel Rebel - 1999 Digital Remaster / David Bowie / Best Of Bowie


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_9");
z.style.display = "none"
function toggle_hidden_q0_9() {
  var x = document.getElementById("answer_q0_9");
  var b = document.getElementById("button_q0_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-9, Previous question -- Q9>> +
<<s-General-Q11-20-q-11, Next question -- General (Q11--20): Q11>>

[[s1]]
== General (Q11--20)

[[s-General-Q11-20-q-11]]
=== Q11

[big]#General (Q11--20): Question 11#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Toto-Africa-Official-Music-Video-FTQbiNvZqaY.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_0" onclick="toggle_hidden_q1_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_0]]
Toto +
Africa / TOTO / Toto IV


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_0");
z.style.display = "none"
function toggle_hidden_q1_0() {
  var x = document.getElementById("answer_q1_0");
  var b = document.getElementById("button_q1_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-10, Previous question -- General (Q1--10): Q10>> +
<<s-General-Q11-20-q-12, Next question -- Q12>>

[[s-General-Q11-20-q-12]]
=== Q12

[big]#General (Q11--20): Question 12#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/01-Bruno-Mars-Grenade-Doo-Wops-Hooligans-aLAtJ0k98SI.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_1" onclick="toggle_hidden_q1_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_1]]
Grenade +
Grenade / Bruno Mars / Doo-Wops & Hooligans


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_1");
z.style.display = "none"
function toggle_hidden_q1_1() {
  var x = document.getElementById("answer_q1_1");
  var b = document.getElementById("button_q1_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-11, Previous question -- Q11>> +
<<s-General-Q11-20-q-13, Next question -- Q13>>

[[s-General-Q11-20-q-13]]
=== Q13

[big]#General (Q11--20): Question 13#

==== Question

Name the artist.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Elvis-Costello-The-Attractions-Pump-It-Up-3Y71iDvCYXA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_2" onclick="toggle_hidden_q1_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_2]]
Elvis Costello +
Pump It Up / Elvis Costello & The Attractions / This Year's Model


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_2");
z.style.display = "none"
function toggle_hidden_q1_2() {
  var x = document.getElementById("answer_q1_2");
  var b = document.getElementById("button_q1_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-12, Previous question -- Q12>> +
<<s-General-Q11-20-q-14, Next question -- Q14>>

[[s-General-Q11-20-q-14]]
=== Q14

[big]#General (Q11--20): Question 14#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Walk-Like-An-Egyptian-tMnGmoLS6zo.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_3" onclick="toggle_hidden_q1_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_3]]
The Bangles +
Walk Like an Egyptian / The Bangles / The Essential Bangles


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_3");
z.style.display = "none"
function toggle_hidden_q1_3() {
  var x = document.getElementById("answer_q1_3");
  var b = document.getElementById("button_q1_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-13, Previous question -- Q13>> +
<<s-General-Q11-20-q-15, Next question -- Q15>>

[[s-General-Q11-20-q-15]]
=== Q15

[big]#General (Q11--20): Question 15#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Mark-Ronson-Uptown-Funk-Official-Video-ft.-Bruno-Mars-OPf0YbXqDm0.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_4" onclick="toggle_hidden_q1_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_4]]
Uptown Funk +
Uptown Funk (feat. Bruno Mars) / Mark Ronson, Bruno Mars / Uptown Special


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_4");
z.style.display = "none"
function toggle_hidden_q1_4() {
  var x = document.getElementById("answer_q1_4");
  var b = document.getElementById("button_q1_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-14, Previous question -- Q14>> +
<<s-General-Q11-20-q-16, Next question -- Q16>>

[[s-General-Q11-20-q-16]]
=== Q16

[big]#General (Q11--20): Question 16#

==== Question

Name the lead singer (not the band).


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Culture-Club-Karma-Chameleon-Official-Video-JmcA9LIIXWw.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_5" onclick="toggle_hidden_q1_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_5]]
Boy George +
Karma Chameleon / Culture Club / At Worst...The Best Of Boy George And Culture Club


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_5");
z.style.display = "none"
function toggle_hidden_q1_5() {
  var x = document.getElementById("answer_q1_5");
  var b = document.getElementById("button_q1_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-15, Previous question -- Q15>> +
<<s-General-Q11-20-q-17, Next question -- Q17>>

[[s-General-Q11-20-q-17]]
=== Q17

[big]#General (Q11--20): Question 17#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Nirvana-Smells-Like-Teen-Spirit-Official-Music-Video-hTWKbfoikeg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_6" onclick="toggle_hidden_q1_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_6]]
Smells Like Teen Spirit +
Smells Like Teen Spirit / Nirvana / Nevermind (Remastered)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_6");
z.style.display = "none"
function toggle_hidden_q1_6() {
  var x = document.getElementById("answer_q1_6");
  var b = document.getElementById("button_q1_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-16, Previous question -- Q16>> +
<<s-General-Q11-20-q-18, Next question -- Q18>>

[[s-General-Q11-20-q-18]]
=== Q18

[big]#General (Q11--20): Question 18#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Tequila-The-Champs-3H6amDbAwlY.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_7" onclick="toggle_hidden_q1_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_7]]
The Champs +
Tequila (Original) / The Champs / Tequila


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_7");
z.style.display = "none"
function toggle_hidden_q1_7() {
  var x = document.getElementById("answer_q1_7");
  var b = document.getElementById("button_q1_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-17, Previous question -- Q17>> +
<<s-General-Q11-20-q-19, Next question -- Q19>>

[[s-General-Q11-20-q-19]]
=== Q19

[big]#General (Q11--20): Question 19#

==== Question

Name the artist.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Theme-From-Shaft-by-Isaac-Hayes-from-Shaft-Music-From-The-Soundtrack-uNJKmf6KTcU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_8" onclick="toggle_hidden_q1_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_8]]
Isaac Hayes +
Theme From Shaft - Album - Remastered / Isaac Hayes / Shaft (Deluxe Edition)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_8");
z.style.display = "none"
function toggle_hidden_q1_8() {
  var x = document.getElementById("answer_q1_8");
  var b = document.getElementById("button_q1_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-18, Previous question -- Q18>> +
<<s-General-Q11-20-q-20, Next question -- Q20>>

[[s-General-Q11-20-q-20]]
=== Q20

[big]#General (Q11--20): Question 20#

==== Question

Name the group.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Build-Me-Up-Buttercup-Nl-2iEP1Wts.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_9" onclick="toggle_hidden_q1_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_9]]
The Foundations +
Build Me Up Buttercup / The Foundations / Build Me Up Buttercup (The Complete Pye Collection)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_9");
z.style.display = "none"
function toggle_hidden_q1_9() {
  var x = document.getElementById("answer_q1_9");
  var b = document.getElementById("button_q1_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-19, Previous question -- Q19>> +
<<s-General-Q21-30-q-21, Next question -- General (Q21--30): Q21>>

[[s2]]
== General (Q21--30)

[[s-General-Q21-30-q-21]]
=== Q21

[big]#General (Q21--30): Question 21#

==== Question

Name the city in which the lead singer of this band is buried.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Doors-Light-My-Fire-cq8k-ZbsXDI.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_0" onclick="toggle_hidden_q2_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_0]]
Paris +
Light My Fire / The Doors / The Doors


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_0");
z.style.display = "none"
function toggle_hidden_q2_0() {
  var x = document.getElementById("answer_q2_0");
  var b = document.getElementById("button_q2_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-20, Previous question -- General (Q11--20): Q20>> +
<<s-General-Q21-30-q-22, Next question -- Q22>>

[[s-General-Q21-30-q-22]]
=== Q22

[big]#General (Q21--30): Question 22#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/God-Only-Knows-Remastered-CWPo5SC3zik.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_1" onclick="toggle_hidden_q2_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_1]]
God Only Knows +
God Only Knows - Remastered / The Beach Boys / Pet Sounds (Original Mono & Stereo Mix Versions)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_1");
z.style.display = "none"
function toggle_hidden_q2_1() {
  var x = document.getElementById("answer_q2_1");
  var b = document.getElementById("button_q2_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-21, Previous question -- Q21>> +
<<s-General-Q21-30-q-23, Next question -- Q23>>

[[s-General-Q21-30-q-23]]
=== Q23

[big]#General (Q21--30): Question 23#

==== Question

Name the song (inclding both the main title and the part in parentheses).


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Norwegian-Wood-This-Bird-Has-Flown-Y-V6y1ZCg-8.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_2" onclick="toggle_hidden_q2_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_2]]
Norwegian Wood (This Bird Has Flown) +
Norwegian Wood (This Bird Has Flown) - Remastered 2009 / The Beatles / Rubber Soul (Remastered)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_2");
z.style.display = "none"
function toggle_hidden_q2_2() {
  var x = document.getElementById("answer_q2_2");
  var b = document.getElementById("button_q2_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-22, Previous question -- Q22>> +
<<s-General-Q21-30-q-24, Next question -- Q24>>

[[s-General-Q21-30-q-24]]
=== Q24

[big]#General (Q21--30): Question 24#

==== Question

Name the performer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/JOE-JACKSON-Is-She-Really-Going-Out-with-Him-HD-6TzKSFbsh2Y.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_3" onclick="toggle_hidden_q2_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_3]]
Joe Jackson +
Is She Really Going Out With Him? / Joe Jackson / Look Sharp!


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_3");
z.style.display = "none"
function toggle_hidden_q2_3() {
  var x = document.getElementById("answer_q2_3");
  var b = document.getElementById("button_q2_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-23, Previous question -- Q23>> +
<<s-General-Q21-30-q-25, Next question -- Q25>>

[[s-General-Q21-30-q-25]]
=== Q25

[big]#General (Q21--30): Question 25#

==== Question

Name the album on which this song appeared.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Elvis-Costello-The-Attractions-Everyday-I-Write-The-Book-V1d4r9awjKE.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_4" onclick="toggle_hidden_q2_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_4]]
Punch the Clock +
Everyday I Write The Book / Elvis Costello & The Attractions / Punch The Clock


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_4");
z.style.display = "none"
function toggle_hidden_q2_4() {
  var x = document.getElementById("answer_q2_4");
  var b = document.getElementById("button_q2_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-24, Previous question -- Q24>> +
<<s-General-Q21-30-q-26, Next question -- Q26>>

[[s-General-Q21-30-q-26]]
=== Q26

[big]#General (Q21--30): Question 26#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Kanye-West-Gold-Digger-ft.-Jamie-Foxx-6vwNcNOTVzY.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_5" onclick="toggle_hidden_q2_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_5]]
Gold Digger +
Gold Digger / Kanye West, Jamie Foxx / Late Registration


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_5");
z.style.display = "none"
function toggle_hidden_q2_5() {
  var x = document.getElementById("answer_q2_5");
  var b = document.getElementById("button_q2_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-25, Previous question -- Q25>> +
<<s-General-Q21-30-q-27, Next question -- Q27>>

[[s-General-Q21-30-q-27]]
=== Q27

[big]#General (Q21--30): Question 27#

==== Question

Name the artist.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Marvin-Gaye-What-s-Going-On-H-kA3UtBj4M.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_6" onclick="toggle_hidden_q2_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_6]]
Marvin Gaye +
What's Going On / Marvin Gaye / What's Going On


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_6");
z.style.display = "none"
function toggle_hidden_q2_6() {
  var x = document.getElementById("answer_q2_6");
  var b = document.getElementById("button_q2_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-26, Previous question -- Q26>> +
<<s-General-Q21-30-q-28, Next question -- Q28>>

[[s-General-Q21-30-q-28]]
=== Q28

[big]#General (Q21--30): Question 28#

==== Question

Name the album on which this song appeared.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Kendrick-Lamar-King-Kunta-hRK7PVJFbS8.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_7" onclick="toggle_hidden_q2_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_7]]
To Pimp a Butterfly +
King Kunta / Kendrick Lamar / To Pimp A Butterfly


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_7");
z.style.display = "none"
function toggle_hidden_q2_7() {
  var x = document.getElementById("answer_q2_7");
  var b = document.getElementById("button_q2_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-27, Previous question -- Q27>> +
<<s-General-Q21-30-q-29, Next question -- Q29>>

[[s-General-Q21-30-q-29]]
=== Q29

[big]#General (Q21--30): Question 29#

==== Question

Name the performer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Chuck-Berry-Johnny-B.-Goode-Single-tXba00vudss.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_8" onclick="toggle_hidden_q2_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_8]]
Chuck Berry +
Johnny B. Goode - Single Version / Chuck Berry / 20th Century Masters: The Millennium Collection: Best Of Chuck Berry


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_8");
z.style.display = "none"
function toggle_hidden_q2_8() {
  var x = document.getElementById("answer_q2_8");
  var b = document.getElementById("button_q2_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-28, Previous question -- Q28>> +
<<s-General-Q21-30-q-30, Next question -- Q30>>

[[s-General-Q21-30-q-30]]
=== Q30

[big]#General (Q21--30): Question 30#

==== Question

Name the artist.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Cyndi-Lauper-Girls-Just-Want-To-Have-Fun-Official-Video-PIb6AZdTr-A.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_9" onclick="toggle_hidden_q2_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_9]]
Cyndi Lauper +
Girls Just Want to Have Fun / Cyndi Lauper / She's So Unusual: A 30th Anniversary Celebration (Deluxe Edition)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_9");
z.style.display = "none"
function toggle_hidden_q2_9() {
  var x = document.getElementById("answer_q2_9");
  var b = document.getElementById("button_q2_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-29, Previous question -- Q29>> +
<<s-General-Q31-40-q-31, Next question -- General (Q31--40): Q31>>

[[s3]]
== General (Q31--40)

[[s-General-Q31-40-q-31]]
=== Q31

[big]#General (Q31--40): Question 31#

==== Question

Name the performer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Eric-Clapton-Cocaine-lyrics-3bEUaeG4wH4.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_0" onclick="toggle_hidden_q3_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_0]]
Eric Clapton +
Cocaine / Eric Clapton / Slowhand 35th Anniversary (Super Deluxe)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_0");
z.style.display = "none"
function toggle_hidden_q3_0() {
  var x = document.getElementById("answer_q3_0");
  var b = document.getElementById("button_q3_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-30, Previous question -- General (Q21--30): Q30>> +
<<s-General-Q31-40-q-32, Next question -- Q32>>

[[s-General-Q31-40-q-32]]
=== Q32

[big]#General (Q31--40): Question 32#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Jonas-Blue-ft.-Dakota-Fast-Car-Official-Music-Video-0wpuR68uw-8.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_1" onclick="toggle_hidden_q3_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_1]]
Fast car. +
Fast Car / Jonas Blue, Dakota / Fast Car


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_1");
z.style.display = "none"
function toggle_hidden_q3_1() {
  var x = document.getElementById("answer_q3_1");
  var b = document.getElementById("button_q3_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-31, Previous question -- Q31>> +
<<s-General-Q31-40-q-33, Next question -- Q33>>

[[s-General-Q31-40-q-33]]
=== Q33

[big]#General (Q31--40): Question 33#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Bob-Marley-The-Wailers-Is-This-Love-cOJsK8qbAaA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_2" onclick="toggle_hidden_q3_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_2]]
Is this Love +
Is This Love / Bob Marley & The Wailers / Kaya - Deluxe Edition


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_2");
z.style.display = "none"
function toggle_hidden_q3_2() {
  var x = document.getElementById("answer_q3_2");
  var b = document.getElementById("button_q3_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-32, Previous question -- Q32>> +
<<s-General-Q31-40-q-34, Next question -- Q34>>

[[s-General-Q31-40-q-34]]
=== Q34

[big]#General (Q31--40): Question 34#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Meghan-Trainor-All-About-That-Bass-Official-Music-Video-7PCkvCPvDXk.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_3" onclick="toggle_hidden_q3_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_3]]
Meghan Trainor +
All About That Bass / Meghan Trainor / All About That Bass


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_3");
z.style.display = "none"
function toggle_hidden_q3_3() {
  var x = document.getElementById("answer_q3_3");
  var b = document.getElementById("button_q3_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-33, Previous question -- Q33>> +
<<s-General-Q31-40-q-35, Next question -- Q35>>

[[s-General-Q31-40-q-35]]
=== Q35

[big]#General (Q31--40): Question 35#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Black-Eyed-Peas-I-Gotta-Feeling-Official-Music-Video-uSD4vsh1zDA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_4" onclick="toggle_hidden_q3_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_4]]
Black Eyed Peas +
I Gotta Feeling / Black Eyed Peas / THE E.N.D. (THE ENERGY NEVER DIES)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_4");
z.style.display = "none"
function toggle_hidden_q3_4() {
  var x = document.getElementById("answer_q3_4");
  var b = document.getElementById("button_q3_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-34, Previous question -- Q34>> +
<<s-General-Q31-40-q-36, Next question -- Q36>>

[[s-General-Q31-40-q-36]]
=== Q36

[big]#General (Q31--40): Question 36#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Wham-Wake-Me-Up-Before-You-Go-Go-Official-HD-Video-ELflyACZXQQ.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_5" onclick="toggle_hidden_q3_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_5]]
Wake Me Up Before You Go-Go +
Wake Me Up Before You Go-Go / Wham! / Make It Big


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_5");
z.style.display = "none"
function toggle_hidden_q3_5() {
  var x = document.getElementById("answer_q3_5");
  var b = document.getElementById("button_q3_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-35, Previous question -- Q35>> +
<<s-General-Q31-40-q-37, Next question -- Q37>>

[[s-General-Q31-40-q-37]]
=== Q37

[big]#General (Q31--40): Question 37#

==== Question

What does "love" make in this song?


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Ring-of-Fire-Johnny-Cash-mIBTg7q9oNc.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_6" onclick="toggle_hidden_q3_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_6]]
"It makes a fiery ring" +
Ring of Fire / Johnny Cash / Johnny Cash - 16 Biggest Hits


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_6");
z.style.display = "none"
function toggle_hidden_q3_6() {
  var x = document.getElementById("answer_q3_6");
  var b = document.getElementById("button_q3_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-36, Previous question -- Q36>> +
<<s-General-Q31-40-q-38, Next question -- Q38>>

[[s-General-Q31-40-q-38]]
=== Q38

[big]#General (Q31--40): Question 38#

==== Question

Name the group.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Isley-Brothers-Shout-rWRsJ-mDU5o.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_7" onclick="toggle_hidden_q3_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_7]]
The Isley Brothers +
Shout / The Isley Brothers / Pure... '50s


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_7");
z.style.display = "none"
function toggle_hidden_q3_7() {
  var x = document.getElementById("answer_q3_7");
  var b = document.getElementById("button_q3_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-37, Previous question -- Q37>> +
<<s-General-Q31-40-q-39, Next question -- Q39>>

[[s-General-Q31-40-q-39]]
=== Q39

[big]#General (Q31--40): Question 39#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Louis-Armstrong-What-A-Wonderful-World-Lyrics-A3yCcXgbKrE.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_8" onclick="toggle_hidden_q3_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_8]]
What a Wonderful World +
What A Wonderful World / Louis Armstrong / Hello Louis - The Hit Years (1963-1969)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_8");
z.style.display = "none"
function toggle_hidden_q3_8() {
  var x = document.getElementById("answer_q3_8");
  var b = document.getElementById("button_q3_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-38, Previous question -- Q38>> +
<<s-General-Q31-40-q-40, Next question -- Q40>>

[[s-General-Q31-40-q-40]]
=== Q40

[big]#General (Q31--40): Question 40#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Logical-Song-low6Coqrw9Y.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_9" onclick="toggle_hidden_q3_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_9]]
The Logical Song +
The Logical Song - Remastered 2010 / Supertramp / Breakfast In America (Deluxe Edition)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_9");
z.style.display = "none"
function toggle_hidden_q3_9() {
  var x = document.getElementById("answer_q3_9");
  var b = document.getElementById("button_q3_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-39, Previous question -- Q39>> +
<<s-General-Q41-50-q-41, Next question -- General (Q41--50): Q41>>

[[s4]]
== General (Q41--50)

[[s-General-Q41-50-q-41]]
=== Q41

[big]#General (Q41--50): Question 41#

==== Question

Name the artist. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Kanye-West-Stronger-PsO6ZnUZI0g.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_0" onclick="toggle_hidden_q4_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_0]]
Kayne West +
Stronger / Kanye West / Stronger (Int'l ECD Maxi)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_0");
z.style.display = "none"
function toggle_hidden_q4_0() {
  var x = document.getElementById("answer_q4_0");
  var b = document.getElementById("button_q4_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-40, Previous question -- General (Q31--40): Q40>> +
<<s-General-Q41-50-q-42, Next question -- Q42>>

[[s-General-Q41-50-q-42]]
=== Q42

[big]#General (Q41--50): Question 42#

==== Question

Name the song. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/My-Generation-Mono-Version-fRipFYoji2A.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_1" onclick="toggle_hidden_q4_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_1]]
My Generation +
My Generation - Mono Version / The Who / The Who Sings My Generation (U.S. Version)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_1");
z.style.display = "none"
function toggle_hidden_q4_1() {
  var x = document.getElementById("answer_q4_1");
  var b = document.getElementById("button_q4_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-41, Previous question -- Q41>> +
<<s-General-Q41-50-q-43, Next question -- Q43>>

[[s-General-Q41-50-q-43]]
=== Q43

[big]#General (Q41--50): Question 43#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Go-Your-Own-Way-2004-Remaster-DubafeFeJ7Y.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_2" onclick="toggle_hidden_q4_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_2]]
Go Your Own Way +
Go Your Own Way - 2004 Remaster / Fleetwood Mac / Rumours


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_2");
z.style.display = "none"
function toggle_hidden_q4_2() {
  var x = document.getElementById("answer_q4_2");
  var b = document.getElementById("button_q4_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-42, Previous question -- Q42>> +
<<s-General-Q41-50-q-44, Next question -- Q44>>

[[s-General-Q41-50-q-44]]
=== Q44

[big]#General (Q41--50): Question 44#

==== Question

Name the album that this song appeared on.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Earth-Wind-Fire-September-Official-Music-Video-Gs069dndIYk.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_3" onclick="toggle_hidden_q4_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_3]]
The Eternal Dance +
September / Earth, Wind & Fire / The Eternal Dance


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_3");
z.style.display = "none"
function toggle_hidden_q4_3() {
  var x = document.getElementById("answer_q4_3");
  var b = document.getElementById("button_q4_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-43, Previous question -- Q43>> +
<<s-General-Q41-50-q-45, Next question -- Q45>>

[[s-General-Q41-50-q-45]]
=== Q45

[big]#General (Q41--50): Question 45#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Lorde-Royals-With-Lyrics-Pure-Heroine-4znHLOWm7pY.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_4" onclick="toggle_hidden_q4_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_4]]
Royals +
Royals / Lorde / Pure Heroine


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_4");
z.style.display = "none"
function toggle_hidden_q4_4() {
  var x = document.getElementById("answer_q4_4");
  var b = document.getElementById("button_q4_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-44, Previous question -- Q44>> +
<<s-General-Q41-50-q-46, Next question -- Q46>>

[[s-General-Q41-50-q-46]]
=== Q46

[big]#General (Q41--50): Question 46#

==== Question

Name the group.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Holiday-Boulevard-of-Broken-Dreams-J0xe5DcnYSA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_5" onclick="toggle_hidden_q4_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_5]]
Green Day +
Holiday / Boulevard of Broken Dreams / Green Day / American Idiot


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_5");
z.style.display = "none"
function toggle_hidden_q4_5() {
  var x = document.getElementById("answer_q4_5");
  var b = document.getElementById("button_q4_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-45, Previous question -- Q45>> +
<<s-General-Q41-50-q-47, Next question -- Q47>>

[[s-General-Q41-50-q-47]]
=== Q47

[big]#General (Q41--50): Question 47#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Come-Sail-Away-eYCFrcCqh7Q.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_6" onclick="toggle_hidden_q4_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_6]]
Styx +
Come Sail Away / Styx / The Grand Illusion


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_6");
z.style.display = "none"
function toggle_hidden_q4_6() {
  var x = document.getElementById("answer_q4_6");
  var b = document.getElementById("button_q4_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-46, Previous question -- Q46>> +
<<s-General-Q41-50-q-48, Next question -- Q48>>

[[s-General-Q41-50-q-48]]
=== Q48

[big]#General (Q41--50): Question 48#

==== Question

Name the artist.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Jason-Derulo-Ridin-Solo-Official-Lyrics-HD-HQ-acWWb1Vxfg0.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_7" onclick="toggle_hidden_q4_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_7]]
Jason Derulo +
Ridin' Solo / Jason Derulo / Jason Derulo (Deluxe Audio)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_7");
z.style.display = "none"
function toggle_hidden_q4_7() {
  var x = document.getElementById("answer_q4_7");
  var b = document.getElementById("button_q4_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-47, Previous question -- Q47>> +
<<s-General-Q41-50-q-49, Next question -- Q49>>

[[s-General-Q41-50-q-49]]
=== Q49

[big]#General (Q41--50): Question 49#

==== Question

Name the song (including both the main title and the part in parentheses)


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/10.-Rupert-Holmes-Escape-The-Pi-a-Colada-Song-TazHNpt6OTo.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_8" onclick="toggle_hidden_q4_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_8]]
Escape (The Pina Colada Song) +
Escape (The Pina Colada Song) / Rupert Holmes / Partners In Crime


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_8");
z.style.display = "none"
function toggle_hidden_q4_8() {
  var x = document.getElementById("answer_q4_8");
  var b = document.getElementById("button_q4_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-48, Previous question -- Q48>> +
<<s-General-Q41-50-q-50, Next question -- Q50>>

[[s-General-Q41-50-q-50]]
=== Q50

[big]#General (Q41--50): Question 50#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Gnarls-Barkley-Crazy-Official-Video-N4jf6rtyuw.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_9" onclick="toggle_hidden_q4_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_9]]
Gnarls Barkley +
Crazy / Gnarls Barkley / St. Elsewhere


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_9");
z.style.display = "none"
function toggle_hidden_q4_9() {
  var x = document.getElementById("answer_q4_9");
  var b = document.getElementById("button_q4_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-49, Previous question -- Q49>> +
<<s-General-Q51-60-q-51, Next question -- General (Q51--60): Q51>>

[[s5]]
== General (Q51--60)

[[s-General-Q51-60-q-51]]
=== Q51

[big]#General (Q51--60): Question 51#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/GOOD-VIBRATIONS-HD-THE-BEACH-BOYS-mdt0SOqPJcg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_0" onclick="toggle_hidden_q5_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_0]]
The Beach Boys +
Good Vibrations - Remastered / The Beach Boys / Good Vibrations 40th Anniversary


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_0");
z.style.display = "none"
function toggle_hidden_q5_0() {
  var x = document.getElementById("answer_q5_0");
  var b = document.getElementById("button_q5_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-50, Previous question -- General (Q41--50): Q50>> +
<<s-General-Q51-60-q-52, Next question -- Q52>>

[[s-General-Q51-60-q-52]]
=== Q52

[big]#General (Q51--60): Question 52#

==== Question

Name the Artist.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Avicii-Hey-Brother-6Cp6mKbRTQY.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_1" onclick="toggle_hidden_q5_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_1]]
Avicii +
Hey Brother / Avicii / TRUE


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_1");
z.style.display = "none"
function toggle_hidden_q5_1() {
  var x = document.getElementById("answer_q5_1");
  var b = document.getElementById("button_q5_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-51, Previous question -- Q51>> +
<<s-General-Q51-60-q-53, Next question -- Q53>>

[[s-General-Q51-60-q-53]]
=== Q53

[big]#General (Q51--60): Question 53#

==== Question

Name the lead singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Aerosmith-Walk-This-Way-Audio-4c8O2n1Gfto.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_2" onclick="toggle_hidden_q5_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_2]]
Steven Tyler +
Walk This Way / Aerosmith / Toys In The Attic


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_2");
z.style.display = "none"
function toggle_hidden_q5_2() {
  var x = document.getElementById("answer_q5_2");
  var b = document.getElementById("button_q5_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-52, Previous question -- Q52>> +
<<s-General-Q51-60-q-54, Next question -- Q54>>

[[s-General-Q51-60-q-54]]
=== Q54

[big]#General (Q51--60): Question 54#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Lean-on-Me-fOZ-MySzAac.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_3" onclick="toggle_hidden_q5_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_3]]
Bill Withers +
Lean on Me / Bill Withers / Still Bill


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_3");
z.style.display = "none"
function toggle_hidden_q5_3() {
  var x = document.getElementById("answer_q5_3");
  var b = document.getElementById("button_q5_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-53, Previous question -- Q53>> +
<<s-General-Q51-60-q-55, Next question -- Q55>>

[[s-General-Q51-60-q-55]]
=== Q55

[big]#General (Q51--60): Question 55#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Lil-Nas-X-Old-Town-Road-feat.-Billy-Ray-Cyrus-Remix-7ysFgElQtjI.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_4" onclick="toggle_hidden_q5_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_4]]
Old Town Road +
Old Town Road (feat. Billy Ray Cyrus) - Remix / Lil Nas X, Billy Ray Cyrus / Old Town Road


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_4");
z.style.display = "none"
function toggle_hidden_q5_4() {
  var x = document.getElementById("answer_q5_4");
  var b = document.getElementById("button_q5_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-54, Previous question -- Q54>> +
<<s-General-Q51-60-q-56, Next question -- Q56>>

[[s-General-Q51-60-q-56]]
=== Q56

[big]#General (Q51--60): Question 56#

==== Question

Name the film that this song was featured in. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Pharrell-Williams-Happy-Official-Music-Video-ZbZSe6N-BXs.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_5" onclick="toggle_hidden_q5_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_5]]
Despicable Me 2 +
Happy / Pharrell Williams / Despicable Me 2 (Original Motion Picture Soundtrack)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_5");
z.style.display = "none"
function toggle_hidden_q5_5() {
  var x = document.getElementById("answer_q5_5");
  var b = document.getElementById("button_q5_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-55, Previous question -- Q55>> +
<<s-General-Q51-60-q-57, Next question -- Q57>>

[[s-General-Q51-60-q-57]]
=== Q57

[big]#General (Q51--60): Question 57#

==== Question

Name the performer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/American-Pie-iX-TFkut1PM.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_6" onclick="toggle_hidden_q5_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_6]]
Don McLean +
American Pie / Don McLean / The Best Of Don McLean


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_6");
z.style.display = "none"
function toggle_hidden_q5_6() {
  var x = document.getElementById("answer_q5_6");
  var b = document.getElementById("button_q5_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-56, Previous question -- Q56>> +
<<s-General-Q51-60-q-58, Next question -- Q58>>

[[s-General-Q51-60-q-58]]
=== Q58

[big]#General (Q51--60): Question 58#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/I-Want-To-Hold-Your-Hand-Remastered-2015-v1HDt1tknTc.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_7" onclick="toggle_hidden_q5_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_7]]
I Want to Hold Your Hand +
I Want To Hold Your Hand - Remastered 2015 / The Beatles / 1 (Remastered)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_7");
z.style.display = "none"
function toggle_hidden_q5_7() {
  var x = document.getElementById("answer_q5_7");
  var b = document.getElementById("button_q5_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-57, Previous question -- Q57>> +
<<s-General-Q51-60-q-59, Next question -- Q59>>

[[s-General-Q51-60-q-59]]
=== Q59

[big]#General (Q51--60): Question 59#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Dolly-Parton-Jolene-Audio-Ixrje2rXLMA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_8" onclick="toggle_hidden_q5_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_8]]
Dolly Parton +
Jolene / Dolly Parton / Jolene


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_8");
z.style.display = "none"
function toggle_hidden_q5_8() {
  var x = document.getElementById("answer_q5_8");
  var b = document.getElementById("button_q5_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-58, Previous question -- Q58>> +
<<s-General-Q51-60-q-60, Next question -- Q60>>

[[s-General-Q51-60-q-60]]
=== Q60

[big]#General (Q51--60): Question 60#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Police-Every-Breath-You-Take-OMOGaugKpzs.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_9" onclick="toggle_hidden_q5_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_9]]
Every Breath You Take +
Every Breath You Take / The Police / Every Breath You Take : The Classics


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_9");
z.style.display = "none"
function toggle_hidden_q5_9() {
  var x = document.getElementById("answer_q5_9");
  var b = document.getElementById("button_q5_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-59, Previous question -- Q59>> +
<<s-One-Hit-Wonders-q-1, Next question -- One Hit Wonders: Q1>>

[[s6]]
== One Hit Wonders

[[s-One-Hit-Wonders-q-1]]
=== Q1

[big]#One Hit Wonders: Question 1#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Bobby-McFerrin-Don-t-Worry-Be-Happy-Official-Video-d-diB65scQU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_0" onclick="toggle_hidden_q6_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_0]]
Bobby McFerrin +
Don't Worry Be Happy / Bobby McFerrin / 20 #1's: One Hit Wonders


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_0");
z.style.display = "none"
function toggle_hidden_q6_0() {
  var x = document.getElementById("answer_q6_0");
  var b = document.getElementById("button_q6_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-60, Previous question -- General (Q51--60): Q60>> +
<<s-One-Hit-Wonders-q-2, Next question -- Q2>>

[[s-One-Hit-Wonders-q-2]]
=== Q2

[big]#One Hit Wonders: Question 2#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Quarterflash-Harden-My-Heart-Official-Video-OqeKV2UYq1Q.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_1" onclick="toggle_hidden_q6_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_1]]
Quarterflash +
Harden My Heart / Quarterflash / 20 #1's: One Hit Wonders


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_1");
z.style.display = "none"
function toggle_hidden_q6_1() {
  var x = document.getElementById("answer_q6_1");
  var b = document.getElementById("button_q6_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-1, Previous question -- Q1>> +
<<s-One-Hit-Wonders-q-3, Next question -- Q3>>

[[s-One-Hit-Wonders-q-3]]
=== Q3

[big]#One Hit Wonders: Question 3#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Knack-My-Sharona-1979-BR2JtsVumFA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_2" onclick="toggle_hidden_q6_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_2]]
The Knack +
My Sharona / The Knack / 20 #1's: One Hit Wonders


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_2");
z.style.display = "none"
function toggle_hidden_q6_2() {
  var x = document.getElementById("answer_q6_2");
  var b = document.getElementById("button_q6_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-2, Previous question -- Q2>> +
<<s-One-Hit-Wonders-q-4, Next question -- Q4>>

[[s-One-Hit-Wonders-q-4]]
=== Q4

[big]#One Hit Wonders: Question 4#

==== Question

Name the band with the very 70s-sounding name.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/disco-duck-97RjuC9YeXg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_3" onclick="toggle_hidden_q6_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_3]]
The Rubix Cubes +
Disco Duck / The Rubix Cube's / 1970's One Hit Wonders


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_3");
z.style.display = "none"
function toggle_hidden_q6_3() {
  var x = document.getElementById("answer_q6_3");
  var b = document.getElementById("button_q6_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-3, Previous question -- Q3>> +
<<s-One-Hit-Wonders-q-5, Next question -- Q5>>

[[s-One-Hit-Wonders-q-5]]
=== Q5

[big]#One Hit Wonders: Question 5#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Bette-Davis-Eyes-Re-Recorded-Remastered-tDJdEhbSP-g.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_4" onclick="toggle_hidden_q6_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_4]]
Kim Carnes +
Bette Davis Eyes (Re-Recorded / Remastered) / Kim Carnes / 80s 1 Hit Wonders (Re-Recorded / Remastered Versions)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_4");
z.style.display = "none"
function toggle_hidden_q6_4() {
  var x = document.getElementById("answer_q6_4");
  var b = document.getElementById("button_q6_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-4, Previous question -- Q4>> +
<<s-One-Hit-Wonders-q-6, Next question -- Q6>>

[[s-One-Hit-Wonders-q-6]]
=== Q6

[big]#One Hit Wonders: Question 6#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Rockwell-Somebody-s-Watching-Me-Official-Video-7YvAYIJSSZY.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_5" onclick="toggle_hidden_q6_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_5]]
Rockwell +
Somebody's Watching Me - Single Version / Rockwell / 20 #1's: One Hit Wonders


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_5");
z.style.display = "none"
function toggle_hidden_q6_5() {
  var x = document.getElementById("answer_q6_5");
  var b = document.getElementById("button_q6_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-5, Previous question -- Q5>> +
<<s-One-Hit-Wonders-q-7, Next question -- Q7>>

[[s-One-Hit-Wonders-q-7]]
=== Q7

[big]#One Hit Wonders: Question 7#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Bruce-Channel-Hey-Baby-ik9dxkKriV0.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_6" onclick="toggle_hidden_q6_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_6]]
Bruce Channel +
Hey! Baby / Bruce Channel / 20 #1's: One Hit Wonders


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_6");
z.style.display = "none"
function toggle_hidden_q6_6() {
  var x = document.getElementById("answer_q6_6");
  var b = document.getElementById("button_q6_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-6, Previous question -- Q6>> +
<<s-One-Hit-Wonders-q-8, Next question -- Q8>>

[[s-One-Hit-Wonders-q-8]]
=== Q8

[big]#One Hit Wonders: Question 8#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Spirit-In-The-Sky-Norman-Greenbaum-AZQxH-8raCI.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_7" onclick="toggle_hidden_q6_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_7]]
Norman Greenbaum +
Spirit In The Sky / Norman Greenbaum / Spirit In The Sky


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_7");
z.style.display = "none"
function toggle_hidden_q6_7() {
  var x = document.getElementById("answer_q6_7");
  var b = document.getElementById("button_q6_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-7, Previous question -- Q7>> +
<<s-One-Hit-Wonders-q-9, Next question -- Q9>>

[[s-One-Hit-Wonders-q-9]]
=== Q9

[big]#One Hit Wonders: Question 9#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Men-Without-Hats-Safety-Dance-Official-Music-Video-AjPau5QYtYs.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_8" onclick="toggle_hidden_q6_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_8]]
Men Without Hats +
The Safety Dance / Men Without Hats / Greatest


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_8");
z.style.display = "none"
function toggle_hidden_q6_8() {
  var x = document.getElementById("answer_q6_8");
  var b = document.getElementById("button_q6_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-8, Previous question -- Q8>> +
<<s-One-Hit-Wonders-q-10, Next question -- Q10>>

[[s-One-Hit-Wonders-q-10]]
=== Q10

[big]#One Hit Wonders: Question 10#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Ready-For-The-World-Oh-Sheila-Official-Video-wbL2lMn34Oo.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_9" onclick="toggle_hidden_q6_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_9]]
Ready for the World. +
Oh Sheila / Ready For The World / 20 #1's: One Hit Wonders


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_9");
z.style.display = "none"
function toggle_hidden_q6_9() {
  var x = document.getElementById("answer_q6_9");
  var b = document.getElementById("button_q6_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-9, Previous question -- Q9>> +
<<s-Broadway-q-1, Next question -- Broadway: Q1>>

[[s7]]
== Broadway

[[s-Broadway-q-1]]
=== Q1

[big]#Broadway: Question 1#

==== Question

Name the musical.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Overture-Te-Tgsw2vOE.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_0" onclick="toggle_hidden_q7_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_0]]
Gypsy +
Overture / 2003 Broadway Cast of "Gypsy" / Gypsy (2003 Broadway Cast)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_0");
z.style.display = "none"
function toggle_hidden_q7_0() {
  var x = document.getElementById("answer_q7_0");
  var b = document.getElementById("button_q7_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-10, Previous question -- One Hit Wonders: Q10>> +
<<s-Broadway-q-2, Next question -- Q2>>

[[s-Broadway-q-2]]
=== Q2

[big]#Broadway: Question 2#

==== Question

Name the musical.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Alexander-Hamilton-VhinPd5RRJw.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_1" onclick="toggle_hidden_q7_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_1]]
Hamilton +
Alexander Hamilton / Leslie Odom, Jr., Anthony Ramos, Daveed Diggs, Okieriete Onaodowan, Lin-Manuel Miranda, Phillipa Soo, Christopher Jackson & Original Broadway Cast of Hamilton / Hamilton (Original Broadway Cast Recording)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_1");
z.style.display = "none"
function toggle_hidden_q7_1() {
  var x = document.getElementById("answer_q7_1");
  var b = document.getElementById("button_q7_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-1, Previous question -- Q1>> +
<<s-Broadway-q-3, Next question -- Q3>>

[[s-Broadway-q-3]]
=== Q3

[big]#Broadway: Question 3#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/West-Side-Story-Something-s-Coming-1961-HD-FOQPMjKLQQU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_2" onclick="toggle_hidden_q7_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_2]]
Something's Coming. +
Something's Coming / Matt Cavenaugh / West Side Story (New Broadway Cast Recording - 2009)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_2");
z.style.display = "none"
function toggle_hidden_q7_2() {
  var x = document.getElementById("answer_q7_2");
  var b = document.getElementById("button_q7_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-2, Previous question -- Q2>> +
<<s-Broadway-q-4, Next question -- Q4>>

[[s-Broadway-q-4]]
=== Q4

[big]#Broadway: Question 4#

==== Question

Name the musical.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/One-Reprise-Finale-OiBIXa-7Vo.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_3" onclick="toggle_hidden_q7_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_3]]
A Chorus Line +
One (Reprise) / Finale / A Chorus Line Ensemble / A Chorus Line - 40th Anniversary Celebration (Original Broadway Cast Recording)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_3");
z.style.display = "none"
function toggle_hidden_q7_3() {
  var x = document.getElementById("answer_q7_3");
  var b = document.getElementById("button_q7_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-3, Previous question -- Q3>> +
<<s-Broadway-q-5, Next question -- Q5>>

[[s-Broadway-q-5]]
=== Q5

[big]#Broadway: Question 5#

==== Question

Name the composer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Being-Alive-Company-2006-Broadway-Revival-Raul-Esparza-YLTulpBF3H4.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_4" onclick="toggle_hidden_q7_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_4]]
Stephen Sondheim +
Being Alive / 2006 Broadway Revival Cast / Company (2006 Broadway Revival Cast)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_4");
z.style.display = "none"
function toggle_hidden_q7_4() {
  var x = document.getElementById("answer_q7_4");
  var b = document.getElementById("button_q7_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-4, Previous question -- Q4>> +
<<s-Broadway-q-6, Next question -- Q6>>

[[s-Broadway-q-6]]
=== Q6

[big]#Broadway: Question 6#

==== Question

Name the musical.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Corner-of-the-Sky-Mdkyc686VIg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_5" onclick="toggle_hidden_q7_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_5]]
Pippin +
Corner of the Sky / Matthew James Thomas / Pippin (New Broadway Cast Recording)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_5");
z.style.display = "none"
function toggle_hidden_q7_5() {
  var x = document.getElementById("answer_q7_5");
  var b = document.getElementById("button_q7_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-5, Previous question -- Q5>> +
<<s-Broadway-q-7, Next question -- Q7>>

[[s-Broadway-q-7]]
=== Q7

[big]#Broadway: Question 7#

==== Question

Name the musical.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/42nd-Street-bPuQkW1-s9k.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_6" onclick="toggle_hidden_q7_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_6]]
42nd Street +
42nd Street / Wanda Richert, Lee Roy Reams & 42nd Street Ensemble / 42nd Street - Original Broadway Cast Recording


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_6");
z.style.display = "none"
function toggle_hidden_q7_6() {
  var x = document.getElementById("answer_q7_6");
  var b = document.getElementById("button_q7_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-6, Previous question -- Q6>> +
<<s-Broadway-q-8, Next question -- Q8>>

[[s-Broadway-q-8]]
=== Q8

[big]#Broadway: Question 8#

==== Question

Name the song. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Barbra-Streisand-Don-t-Rain-On-My-Parade-oZTSuMErgsw.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_7" onclick="toggle_hidden_q7_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_7]]
Don't Rain On My Parade +
Don't Rain On My Parade / Barbra Streisand / The Essential Barbra Streisand


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_7");
z.style.display = "none"
function toggle_hidden_q7_7() {
  var x = document.getElementById("answer_q7_7");
  var b = document.getElementById("button_q7_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-7, Previous question -- Q7>> +
<<s-Broadway-q-9, Next question -- Q9>>

[[s-Broadway-q-9]]
=== Q9

[big]#Broadway: Question 9#

==== Question

Name the composer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Annie-Get-Your-Gun-1999-Broadway-Revival-Cast-9.-They-Say-It-s-Wonderful-3nuUHCKiBuo.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_8" onclick="toggle_hidden_q7_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_8]]
Irving Berlin +
They Say It's Wonderful / Annie Get Your Gun - The 1999 Broadway Cast / Annie Get Your Gun - The New Broadway Cast Recording (Staring Bernadette Peters)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_8");
z.style.display = "none"
function toggle_hidden_q7_8() {
  var x = document.getElementById("answer_q7_8");
  var b = document.getElementById("button_q7_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-8, Previous question -- Q8>> +
<<s-Broadway-q-10, Next question -- Q10>>

[[s-Broadway-q-10]]
=== Q10

[big]#Broadway: Question 10#

==== Question

Name the musical.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Whatever-Lola-Wants-Damn-Yankees.-6kjQmgm0r4g.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_9" onclick="toggle_hidden_q7_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_9]]
Damn Yankees +
Whatever Lola Wants / Gwen Verdon / Damn Yankees (Original Soundtrack) [Remastered]


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_9");
z.style.display = "none"
function toggle_hidden_q7_9() {
  var x = document.getElementById("answer_q7_9");
  var b = document.getElementById("button_q7_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-9, Previous question -- Q9>> +
<<s-New-York-q-1, Next question -- New York: Q1>>

[[s8]]
== New York

[[s-New-York-q-1]]
=== Q1

[big]#New York: Question 1#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Ad-Libs-The-Boy-From-New-York-City-with-lyrics-3TPYmeSqLjc.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_0" onclick="toggle_hidden_q8_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_0]]
The Boy from New York City +
The Boy from New York City / The Ad Libs / Discover 60s One Hit Wonders


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_0");
z.style.display = "none"
function toggle_hidden_q8_0() {
  var x = document.getElementById("answer_q8_0");
  var b = document.getElementById("button_q8_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-10, Previous question -- Broadway: Q10>> +
<<s-New-York-q-2, Next question -- Q2>>

[[s-New-York-q-2]]
=== Q2

[big]#New York: Question 2#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Lullaby-Of-Broadway-Live-n8sd4KiP5iA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_1" onclick="toggle_hidden_q8_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_1]]
Lullaby of Broadway +
Lullaby of Broadway (with The Dave Brubeck Trio) [Live] / Tony Bennett / The White House Sessions, Live 1962


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_1");
z.style.display = "none"
function toggle_hidden_q8_1() {
  var x = document.getElementById("answer_q8_1");
  var b = document.getElementById("button_q8_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-1, Previous question -- Q1>> +
<<s-New-York-q-3, Next question -- Q3>>

[[s-New-York-q-3]]
=== Q3

[big]#New York: Question 3#

==== Question

Name the song. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/GEORGE-BENSON-On-Broadway-Album-Version-ok-l1Acuwg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_2" onclick="toggle_hidden_q8_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_2]]
On Broadway +
On Broadway / George Benson / The George Benson Collection


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_2");
z.style.display = "none"
function toggle_hidden_q8_2() {
  var x = document.getElementById("answer_q8_2");
  var b = document.getElementById("button_q8_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-2, Previous question -- Q2>> +
<<s-New-York-q-4, Next question -- Q4>>

[[s-New-York-q-4]]
=== Q4

[big]#New York: Question 4#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Jay-Z-feat.-Alicia-Keys-Empire-State-of-Mind-Official-Music-Video-Original-Version-QsZlY0Vz4-o.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_3" onclick="toggle_hidden_q8_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_3]]
Empire State of Mind +
Empire State of Mind (feat. Alicia Keys) / JAY-Z & Alicia Keys / The Hits Collection, Vol. One (Deluxe Edition)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_3");
z.style.display = "none"
function toggle_hidden_q8_3() {
  var x = document.getElementById("answer_q8_3");
  var b = document.getElementById("button_q8_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-3, Previous question -- Q3>> +
<<s-New-York-q-5, Next question -- Q5>>

[[s-New-York-q-5]]
=== Q5

[big]#New York: Question 5#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Bruce-Springsteen-Tenth-Avenue-Freeze-Out.wmv-BL-HL3ELvFI.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_4" onclick="toggle_hidden_q8_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_4]]
Tenth Avenue Freeze Out +
Tenth Avenue Freeze-Out / Bruce Springsteen / Born To Run


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_4");
z.style.display = "none"
function toggle_hidden_q8_4() {
  var x = document.getElementById("answer_q8_4");
  var b = document.getElementById("button_q8_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-4, Previous question -- Q4>> +
<<s-New-York-q-6, Next question -- Q6>>

[[s-New-York-q-6]]
=== Q6

[big]#New York: Question 6#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Ben-E-King-Spanish-Harlem-OGd6CdtOqEE.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_5" onclick="toggle_hidden_q8_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_5]]
Spanish Herlem +
Spanish Harlem / Ben E. King / Spanish Harlem


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_5");
z.style.display = "none"
function toggle_hidden_q8_5() {
  var x = document.getElementById("answer_q8_5");
  var b = document.getElementById("button_q8_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-5, Previous question -- Q5>> +
<<s-New-York-q-7, Next question -- Q7>>

[[s-New-York-q-7]]
=== Q7

[big]#New York: Question 7#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Odyssey-Native-New-Yorker-1977-HD-JpQ6NtbZxiE.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_6" onclick="toggle_hidden_q8_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_6]]
Native New Yorker +
Native New Yorker / Odyssey / Odyssey (Expanded Edition)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_6");
z.style.display = "none"
function toggle_hidden_q8_6() {
  var x = document.getElementById("answer_q8_6");
  var b = document.getElementById("button_q8_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-6, Previous question -- Q6>> +
<<s-New-York-q-8, Next question -- Q8>>

[[s-New-York-q-8]]
=== Q8

[big]#New York: Question 8#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Pogues-Fairytale-Of-New-York-Official-Video-j9jbdgZidu8.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_7" onclick="toggle_hidden_q8_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_7]]
Fairytale of New York +
Fairytale of New York / The Pogues / If I Should Fall from Grace With God [Expanded]


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_7");
z.style.display = "none"
function toggle_hidden_q8_7() {
  var x = document.getElementById("answer_q8_7");
  var b = document.getElementById("button_q8_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-7, Previous question -- Q7>> +
<<s-New-York-q-9, Next question -- Q9>>

[[s-New-York-q-9]]
=== Q9

[big]#New York: Question 9#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/RUN-DMC-Christmas-In-Hollis-Video-OR07r0ZMFb8.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_8" onclick="toggle_hidden_q8_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_8]]
Christmas in Hollis +
Christmas In Hollis (Bonus Track) / Run-DMC / Tougher Than Leather


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_8");
z.style.display = "none"
function toggle_hidden_q8_8() {
  var x = document.getElementById("answer_q8_8");
  var b = document.getElementById("button_q8_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-8, Previous question -- Q8>> +
<<s-New-York-q-10, Next question -- Q10>>

[[s-New-York-q-10]]
=== Q10

[big]#New York: Question 10#

==== Question

Name the person who sang this song in the movie in which it first appeared.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Theme-From-New-York-New-York-Remastered-2008-le1QF3uoQNg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_9" onclick="toggle_hidden_q8_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_9]]
Liza Minelli +
Theme from New York, New York / Frank Sinatra / Ultimate Sinatra: The Centennial Collection


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_9");
z.style.display = "none"
function toggle_hidden_q8_9() {
  var x = document.getElementById("answer_q8_9");
  var b = document.getElementById("button_q8_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-9, Previous question -- Q9>> +
<<s-Movie-q-1, Next question -- Movie: Q1>>

[[s9]]
== Movie

[[s-Movie-q-1]]
=== Q1

[big]#Movie: Question 1#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Jules-and-Jim-Movie-Main-Theme-iFtFCZhFnMU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_0" onclick="toggle_hidden_q9_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_0]]
Jules and Jim +
Jules and Jim (Movie Main Theme) / Film & TV Masters / Ultimate Movie Theme Playlist


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_0");
z.style.display = "none"
function toggle_hidden_q9_0() {
  var x = document.getElementById("answer_q9_0");
  var b = document.getElementById("button_q9_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-10, Previous question -- New York: Q10>> +
<<s-Movie-q-2, Next question -- Q2>>

[[s-Movie-q-2]]
=== Q2

[big]#Movie: Question 2#

==== Question

Name the composer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Nino-Rota-Amarcord-bk4MEhUkxco.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_1" onclick="toggle_hidden_q9_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_1]]
Nino Rota +
Amarcord / Nino Rota / Amarcord


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_1");
z.style.display = "none"
function toggle_hidden_q9_1() {
  var x = document.getElementById("answer_q9_1");
  var b = document.getElementById("button_q9_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-1, Previous question -- Q1>> +
<<s-Movie-q-3, Next question -- Q3>>

[[s-Movie-q-3]]
=== Q3

[big]#Movie: Question 3#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Good-the-Bad-and-the-Ugly-Movie-Main-Theme-o-zafpeLXhE.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_2" onclick="toggle_hidden_q9_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_2]]
The Good, the Bad and the Ugly +
The Good, the Bad and the Ugly (Movie Main Theme) / Film & TV Masters / Ultimate Movie Theme Playlist


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_2");
z.style.display = "none"
function toggle_hidden_q9_2() {
  var x = document.getElementById("answer_q9_2");
  var b = document.getElementById("button_q9_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-2, Previous question -- Q2>> +
<<s-Movie-q-4, Next question -- Q4>>

[[s-Movie-q-4]]
=== Q4

[big]#Movie: Question 4#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Superman-Movie-Main-Theme-cm97g2cOKto.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_3" onclick="toggle_hidden_q9_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_3]]
Superman +
Superman (Movie Main Theme) / Film & TV Masters / Ultimate Movie Theme Playlist


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_3");
z.style.display = "none"
function toggle_hidden_q9_3() {
  var x = document.getElementById("answer_q9_3");
  var b = document.getElementById("button_q9_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-3, Previous question -- Q3>> +
<<s-Movie-q-5, Next question -- Q5>>

[[s-Movie-q-5]]
=== Q5

[big]#Movie: Question 5#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/A-Man-and-a-Woman-Movie-Main-Theme-So9rDiGxQTQ.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_4" onclick="toggle_hidden_q9_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_4]]
A man and a Woman +
A Man and a Woman (Movie Main Theme) / Film & TV Masters / Ultimate Movie Theme Playlist


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_4");
z.style.display = "none"
function toggle_hidden_q9_4() {
  var x = document.getElementById("answer_q9_4");
  var b = document.getElementById("button_q9_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-4, Previous question -- Q4>> +
<<s-Movie-q-6, Next question -- Q6>>

[[s-Movie-q-6]]
=== Q6

[big]#Movie: Question 6#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/La-dolce-vita-Titoli-testa-Canzonetta-Notturno-Cadillac-M-pDPlITpcU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_5" onclick="toggle_hidden_q9_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_5]]
La Dolce Vita +
La dolce vita / Nino Rota, Studio Orchestra, StudioConductor / Original Music for the Movies of Federico Fellini


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_5");
z.style.display = "none"
function toggle_hidden_q9_5() {
  var x = document.getElementById("answer_q9_5");
  var b = document.getElementById("button_q9_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-5, Previous question -- Q5>> +
<<s-Movie-q-7, Next question -- Q7>>

[[s-Movie-q-7]]
=== Q7

[big]#Movie: Question 7#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/End-Title-O-6Da8wD0A.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_6" onclick="toggle_hidden_q9_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_6]]
Lawrence of Arabia +
End Title (from "Lawrence Of Arabia") / London Philharmonic Orchestra / Lawrence Of Arabia (Original Soundtrack Recording)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_6");
z.style.display = "none"
function toggle_hidden_q9_6() {
  var x = document.getElementById("answer_q9_6");
  var b = document.getElementById("button_q9_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-6, Previous question -- Q6>> +
<<s-Movie-q-8, Next question -- Q8>>

[[s-Movie-q-8]]
=== Q8

[big]#Movie: Question 8#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Patton-March-HAe40MzBktg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_7" onclick="toggle_hidden_q9_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_7]]
Patton +
Patton / DLG Orchestra / Greatest Movie Themes


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_7");
z.style.display = "none"
function toggle_hidden_q9_7() {
  var x = document.getElementById("answer_q9_7");
  var b = document.getElementById("button_q9_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-7, Previous question -- Q7>> +
<<s-Movie-q-9, Next question -- Q9>>

[[s-Movie-q-9]]
=== Q9

[big]#Movie: Question 9#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Godfather-DGtEtwdZZKo.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_8" onclick="toggle_hidden_q9_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_8]]
The Godfather. +
The Godfather / A Century Of Movie Soundtracks / A Century Of Movie Soundtracks Vol. 2


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_8");
z.style.display = "none"
function toggle_hidden_q9_8() {
  var x = document.getElementById("answer_q9_8");
  var b = document.getElementById("button_q9_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-8, Previous question -- Q8>> +
<<s-Movie-q-10, Next question -- Q10>>

[[s-Movie-q-10]]
=== Q10

[big]#Movie: Question 10#

==== Question

Name the composer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Pink-Panther-XdnnytXfj5g.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_9" onclick="toggle_hidden_q9_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_9]]
Henry Mancini +
The Pink Panther / A Century Of Movie Soundtracks / A Century Of Movie Soundtracks Vol. 1


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_9");
z.style.display = "none"
function toggle_hidden_q9_9() {
  var x = document.getElementById("answer_q9_9");
  var b = document.getElementById("button_q9_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-9, Previous question -- Q9>> +
<<s-Bonus-q-1, Next question -- Bonus: Q1>>

[[s10]]
== Bonus

[[s-Bonus-q-1]]
=== Q1

[big]#Bonus: Question 1#

==== Question

Name the group.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Surf-City-Remastered-1990-Stereo-Remix-ZWMcoxeXKAg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_0" onclick="toggle_hidden_q10_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_0]]
Jan & Dean +
Surf City - Remastered 1990/Stereo Remix / Jan & Dean / Surf City: The Best Of Jan & Dean


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_0");
z.style.display = "none"
function toggle_hidden_q10_0() {
  var x = document.getElementById("answer_q10_0");
  var b = document.getElementById("button_q10_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-10, Previous question -- Movie: Q10>> +
<<s-Bonus-q-2, Next question -- Q2>>

[[s-Bonus-q-2]]
=== Q2

[big]#Bonus: Question 2#

==== Question

Name  famous  film in which this song was sung spontaneously.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Hommage-national-la-Marseillaise-du-Choeur-de-l-Arm-e-fran-aise-SLe6KcssqiM.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_1" onclick="toggle_hidden_q10_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_1]]
Casablanca +
France: La Marseillaise / Choeur de l'Armée Française, Musique De La Garde Républicaine / Les hymnes officiels de la Coupe du Monde de Rugby (National Anthems Rugby World Cup France)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_1");
z.style.display = "none"
function toggle_hidden_q10_1() {
  var x = document.getElementById("answer_q10_1");
  var b = document.getElementById("button_q10_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-1, Previous question -- Q1>> +
<<s-Bonus-q-3, Next question -- Q3>>

[[s-Bonus-q-3]]
=== Q3

[big]#Bonus: Question 3#

==== Question

Name the famous televangelist who was a cousin of the this singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Great-Balls-of-Fire-Jerry-Lee-Lewis-original-song-1957-Jt0mg8Z09SY.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_2" onclick="toggle_hidden_q10_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_2]]
Jimmy Swaggert +
Great Balls Of Fire / Jerry Lee Lewis / The Golden Rock Hits Of Jerry Lee Lewis


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_2");
z.style.display = "none"
function toggle_hidden_q10_2() {
  var x = document.getElementById("answer_q10_2");
  var b = document.getElementById("button_q10_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-2, Previous question -- Q2>> +
<<s-Bonus-q-4, Next question -- Q4>>

[[s-Bonus-q-4]]
=== Q4

[big]#Bonus: Question 4#

==== Question

Name the two movies that had this song as their opening credit music. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Rock-Around-the-Clock-Bill-Haley-original-song-1955-Ud-JZcC0tHI.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_3" onclick="toggle_hidden_q10_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_3]]
American Graffiti and Blackboard Jungle +
(We're Gonna) Rock Around The Clock - Single Version / Bill Haley & His Comets / From The Original Master Tapes


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_3");
z.style.display = "none"
function toggle_hidden_q10_3() {
  var x = document.getElementById("answer_q10_3");
  var b = document.getElementById("button_q10_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-3, Previous question -- Q3>> +
<<s-Bonus-q-5, Next question -- Q5>>

[[s-Bonus-q-5]]
=== Q5

[big]#Bonus: Question 5#

==== Question

In this song, what "has bitten the dust?"


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/London-Calling-Remastered-XN7iEFVLf5c.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_4" onclick="toggle_hidden_q10_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_4]]
Phony Beatlemania +
London Calling - Remastered / The Clash / London Calling (Remastered)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_4");
z.style.display = "none"
function toggle_hidden_q10_4() {
  var x = document.getElementById("answer_q10_4");
  var b = document.getElementById("button_q10_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-4, Previous question -- Q4>> +
<<s-Bonus-q-6, Next question -- Q6>>

[[s-Bonus-q-6]]
=== Q6

[big]#Bonus: Question 6#

==== Question

Name the band, the song and the album - we need all three.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Pet-Sounds-Remastered-EeN-NytxKEc.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_5" onclick="toggle_hidden_q10_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_5]]
the Beach Boys; Pet Sounds; Pet Sounds +
Pet Sounds - Remastered / The Beach Boys / Pet Sounds (Original Mono & Stereo Mix Versions)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_5");
z.style.display = "none"
function toggle_hidden_q10_5() {
  var x = document.getElementById("answer_q10_5");
  var b = document.getElementById("button_q10_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-5, Previous question -- Q5>> +
<<s-Bonus-q-7, Next question -- Q7>>

[[s-Bonus-q-7]]
=== Q7

[big]#Bonus: Question 7#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Carl-Perkins-Gone-Gone-Gone-yrhZKavICNU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_6" onclick="toggle_hidden_q10_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_6]]
Gone Gone Gone +
Gone, Gone, Gone / Carl Perkins / The Dance Album


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_6");
z.style.display = "none"
function toggle_hidden_q10_6() {
  var x = document.getElementById("answer_q10_6");
  var b = document.getElementById("button_q10_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-6, Previous question -- Q6>> +
<<s-Bonus-q-8, Next question -- Q8>>

[[s-Bonus-q-8]]
=== Q8

[big]#Bonus: Question 8#

==== Question

Name the album.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Joe-Jackson-Look-Sharp-V8-b9LK1trE.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_7" onclick="toggle_hidden_q10_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_7]]
Look Sharp! +
Look Sharp! / Joe Jackson / Look Sharp!


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_7");
z.style.display = "none"
function toggle_hidden_q10_7() {
  var x = document.getElementById("answer_q10_7");
  var b = document.getElementById("button_q10_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-7, Previous question -- Q7>> +
<<s-Bonus-q-9, Next question -- Q9>>

[[s-Bonus-q-9]]
=== Q9

[big]#Bonus: Question 9#

==== Question

Name the movie in which this song was sung by this artist.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Elvis-Presley-Can-t-Help-Falling-In-Love-Audio-vGJTaP6anOU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_8" onclick="toggle_hidden_q10_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_8]]
Blue Hawaii +
Can't Help Falling in Love / Elvis Presley / Blue Hawaii


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_8");
z.style.display = "none"
function toggle_hidden_q10_8() {
  var x = document.getElementById("answer_q10_8");
  var b = document.getElementById("button_q10_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-8, Previous question -- Q8>> +
<<s-Bonus-q-10, Next question -- Q10>>

[[s-Bonus-q-10]]
=== Q10

[big]#Bonus: Question 10#

==== Question

Name the movie in which this song played a significant part,


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Roy-Orbison-In-Dreams-MVRunwyoTMA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_9" onclick="toggle_hidden_q10_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_9]]
Blue Velvet +
In Dreams / Roy Orbison / In Dreams


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_9");
z.style.display = "none"
function toggle_hidden_q10_9() {
  var x = document.getElementById("answer_q10_9");
  var b = document.getElementById("button_q10_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-9, Previous question -- Q9>>
