
= Music trivia
:toc2:
:toclevels: 2
:toc-title: Welcome to Quarantine Music Trivia!

[subs=""]
++++++++++++
<style>
html, body { height: 100%; }
.fullheight { overflow-y:auto; height:100vh; }​
a { color:blue; }
a:visited { color:blue; }
a:active { color:blue; }
a[tabindex]:focus { color:blue; outline:none; }
</style>
++++++++++++

== Welcome
    

[[s0]]
== General (Q1--10)

[[s-General-Q1-10-q-1]]
=== Q1

[big]#General (Q1--10): Question 1#

==== Question

Name the artist. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Kanye-West-Stronger-PsO6ZnUZI0g.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_0" onclick="toggle_hidden_q0_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_0]]
Kayne West +
Kanye West / Stronger (Int'l ECD Maxi) / Stronger


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_0");
z.style.display = "none"
function toggle_hidden_q0_0() {
  var x = document.getElementById("answer_q0_0");
  var b = document.getElementById("button_q0_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-2, Next question -- Q2>>

[[s-General-Q1-10-q-2]]
=== Q2

[big]#General (Q1--10): Question 2#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Lil-Nas-X-Old-Town-Road-feat.-Billy-Ray-Cyrus-Remix-7ysFgElQtjI.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_1" onclick="toggle_hidden_q0_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_1]]
Old Town Road +
Lil Nas X, Billy Ray Cyrus / Old Town Road / Old Town Road (feat. Billy Ray Cyrus) - Remix


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_1");
z.style.display = "none"
function toggle_hidden_q0_1() {
  var x = document.getElementById("answer_q0_1");
  var b = document.getElementById("button_q0_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-1, Previous question -- Q1>> +
<<s-General-Q1-10-q-3, Next question -- Q3>>

[[s-General-Q1-10-q-3]]
=== Q3

[big]#General (Q1--10): Question 3#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Daft-Punk-Get-Lucky-Official-Audio-ft.-Pharrell-Williams-Nile-Rodgers-5NV6Rdv1a3I.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_2" onclick="toggle_hidden_q0_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_2]]
Get Lucky +
Daft Punk, Pharrell Williams, Nile Rodgers / Get Lucky (feat. Pharrell Williams & Nile Rodgers) [Radio Edit] / Get Lucky (feat. Pharrell Williams & Nile Rodgers) - Radio Edit


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_2");
z.style.display = "none"
function toggle_hidden_q0_2() {
  var x = document.getElementById("answer_q0_2");
  var b = document.getElementById("button_q0_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-2, Previous question -- Q2>> +
<<s-General-Q1-10-q-4, Next question -- Q4>>

[[s-General-Q1-10-q-4]]
=== Q4

[big]#General (Q1--10): Question 4#

==== Question

Name the artist.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Jason-Derulo-Ridin-Solo-Official-Lyrics-HD-HQ-acWWb1Vxfg0.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_3" onclick="toggle_hidden_q0_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_3]]
Jason Derulo +
Jason Derulo / Jason Derulo (Deluxe Audio) / Ridin' Solo


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_3");
z.style.display = "none"
function toggle_hidden_q0_3() {
  var x = document.getElementById("answer_q0_3");
  var b = document.getElementById("button_q0_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-3, Previous question -- Q3>> +
<<s-General-Q1-10-q-5, Next question -- Q5>>

[[s-General-Q1-10-q-5]]
=== Q5

[big]#General (Q1--10): Question 5#

==== Question

Name the Artist.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Avicii-Hey-Brother-6Cp6mKbRTQY.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_4" onclick="toggle_hidden_q0_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_4]]
Avicii +
Avicii / TRUE / Hey Brother


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_4");
z.style.display = "none"
function toggle_hidden_q0_4() {
  var x = document.getElementById("answer_q0_4");
  var b = document.getElementById("button_q0_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-4, Previous question -- Q4>> +
<<s-General-Q1-10-q-6, Next question -- Q6>>

[[s-General-Q1-10-q-6]]
=== Q6

[big]#General (Q1--10): Question 6#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Jonas-Blue-ft.-Dakota-Fast-Car-Official-Music-Video-0wpuR68uw-8.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_5" onclick="toggle_hidden_q0_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_5]]
Fast car. +
Jonas Blue, Dakota / Fast Car / Fast Car


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_5");
z.style.display = "none"
function toggle_hidden_q0_5() {
  var x = document.getElementById("answer_q0_5");
  var b = document.getElementById("button_q0_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-5, Previous question -- Q5>> +
<<s-General-Q1-10-q-7, Next question -- Q7>>

[[s-General-Q1-10-q-7]]
=== Q7

[big]#General (Q1--10): Question 7#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Nirvana-Smells-Like-Teen-Spirit-Official-Music-Video-hTWKbfoikeg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_6" onclick="toggle_hidden_q0_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_6]]
Smells Like Teen Spirit +
Nirvana / Nevermind (Remastered) / Smells Like Teen Spirit


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_6");
z.style.display = "none"
function toggle_hidden_q0_6() {
  var x = document.getElementById("answer_q0_6");
  var b = document.getElementById("button_q0_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-6, Previous question -- Q6>> +
<<s-General-Q1-10-q-8, Next question -- Q8>>

[[s-General-Q1-10-q-8]]
=== Q8

[big]#General (Q1--10): Question 8#

==== Question

Name the artist.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Cyndi-Lauper-Girls-Just-Want-To-Have-Fun-Official-Video-PIb6AZdTr-A.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_7" onclick="toggle_hidden_q0_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_7]]
Cyndi Lauper +
Cyndi Lauper / She's So Unusual: A 30th Anniversary Celebration (Deluxe Edition) / Girls Just Want to Have Fun


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_7");
z.style.display = "none"
function toggle_hidden_q0_7() {
  var x = document.getElementById("answer_q0_7");
  var b = document.getElementById("button_q0_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-7, Previous question -- Q7>> +
<<s-General-Q1-10-q-9, Next question -- Q9>>

[[s-General-Q1-10-q-9]]
=== Q9

[big]#General (Q1--10): Question 9#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Toto-Africa-Official-Music-Video-FTQbiNvZqaY.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_8" onclick="toggle_hidden_q0_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_8]]
Toto +
TOTO / Toto IV / Africa


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_8");
z.style.display = "none"
function toggle_hidden_q0_8() {
  var x = document.getElementById("answer_q0_8");
  var b = document.getElementById("button_q0_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-8, Previous question -- Q8>> +
<<s-General-Q1-10-q-10, Next question -- Q10>>

[[s-General-Q1-10-q-10]]
=== Q10

[big]#General (Q1--10): Question 10#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Walk-Like-An-Egyptian-tMnGmoLS6zo.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_9" onclick="toggle_hidden_q0_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_9]]
The Bangles +
The Bangles / The Essential Bangles / Walk Like an Egyptian


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_9");
z.style.display = "none"
function toggle_hidden_q0_9() {
  var x = document.getElementById("answer_q0_9");
  var b = document.getElementById("button_q0_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-9, Previous question -- Q9>> +
<<s-General-Q11-20-q-11, Next question -- General (Q11--20): Q11>>

[[s1]]
== General (Q11--20)

[[s-General-Q11-20-q-11]]
=== Q11

[big]#General (Q11--20): Question 11#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Police-Every-Breath-You-Take-OMOGaugKpzs.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_0" onclick="toggle_hidden_q1_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_0]]
Every Breath You Take +
The Police / Every Breath You Take : The Classics / Every Breath You Take


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_0");
z.style.display = "none"
function toggle_hidden_q1_0() {
  var x = document.getElementById("answer_q1_0");
  var b = document.getElementById("button_q1_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-10, Previous question -- General (Q1--10): Q10>> +
<<s-General-Q11-20-q-12, Next question -- Q12>>

[[s-General-Q11-20-q-12]]
=== Q12

[big]#General (Q11--20): Question 12#

==== Question

Name the lead singer (not the band).


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Culture-Club-Karma-Chameleon-Official-Video-JmcA9LIIXWw.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_1" onclick="toggle_hidden_q1_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_1]]
Boy George +
Culture Club / At Worst...The Best Of Boy George And Culture Club / Karma Chameleon


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_1");
z.style.display = "none"
function toggle_hidden_q1_1() {
  var x = document.getElementById("answer_q1_1");
  var b = document.getElementById("button_q1_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-11, Previous question -- Q11>> +
<<s-General-Q11-20-q-13, Next question -- Q13>>

[[s-General-Q11-20-q-13]]
=== Q13

[big]#General (Q11--20): Question 13#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Dolly-Parton-Jolene-Audio-Ixrje2rXLMA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_2" onclick="toggle_hidden_q1_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_2]]
Dolly Parton +
Dolly Parton / Jolene / Jolene


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_2");
z.style.display = "none"
function toggle_hidden_q1_2() {
  var x = document.getElementById("answer_q1_2");
  var b = document.getElementById("button_q1_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-12, Previous question -- Q12>> +
<<s-General-Q11-20-q-14, Next question -- Q14>>

[[s-General-Q11-20-q-14]]
=== Q14

[big]#General (Q11--20): Question 14#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Gnarls-Barkley-Crazy-Official-Video-N4jf6rtyuw.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_3" onclick="toggle_hidden_q1_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_3]]
Gnarls Barkley +
Gnarls Barkley / St. Elsewhere / Crazy


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_3");
z.style.display = "none"
function toggle_hidden_q1_3() {
  var x = document.getElementById("answer_q1_3");
  var b = document.getElementById("button_q1_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-13, Previous question -- Q13>> +
<<s-General-Q11-20-q-15, Next question -- Q15>>

[[s-General-Q11-20-q-15]]
=== Q15

[big]#General (Q11--20): Question 15#

==== Question

Name the album that this song appeared on.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Earth-Wind-Fire-September-Official-Music-Video-Gs069dndIYk.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_4" onclick="toggle_hidden_q1_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_4]]
The Eternal Dance +
Earth, Wind & Fire / The Eternal Dance / September


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_4");
z.style.display = "none"
function toggle_hidden_q1_4() {
  var x = document.getElementById("answer_q1_4");
  var b = document.getElementById("button_q1_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-14, Previous question -- Q14>> +
<<s-General-Q11-20-q-16, Next question -- Q16>>

[[s-General-Q11-20-q-16]]
=== Q16

[big]#General (Q11--20): Question 16#

==== Question

Name the performer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/American-Pie-iX-TFkut1PM.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_5" onclick="toggle_hidden_q1_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_5]]
Don McLean +
Don McLean / The Best Of Don McLean / American Pie


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_5");
z.style.display = "none"
function toggle_hidden_q1_5() {
  var x = document.getElementById("answer_q1_5");
  var b = document.getElementById("button_q1_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-15, Previous question -- Q15>> +
<<s-General-Q11-20-q-17, Next question -- Q17>>

[[s-General-Q11-20-q-17]]
=== Q17

[big]#General (Q11--20): Question 17#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Lean-on-Me-fOZ-MySzAac.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_6" onclick="toggle_hidden_q1_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_6]]
Bill Withers +
Bill Withers / Still Bill / Lean on Me


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_6");
z.style.display = "none"
function toggle_hidden_q1_6() {
  var x = document.getElementById("answer_q1_6");
  var b = document.getElementById("button_q1_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-16, Previous question -- Q16>> +
<<s-General-Q11-20-q-18, Next question -- Q18>>

[[s-General-Q11-20-q-18]]
=== Q18

[big]#General (Q11--20): Question 18#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/GOOD-VIBRATIONS-HD-THE-BEACH-BOYS-mdt0SOqPJcg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_7" onclick="toggle_hidden_q1_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_7]]
The Beach Boys +
The Beach Boys / Good Vibrations 40th Anniversary / Good Vibrations - Remastered


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_7");
z.style.display = "none"
function toggle_hidden_q1_7() {
  var x = document.getElementById("answer_q1_7");
  var b = document.getElementById("button_q1_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-17, Previous question -- Q17>> +
<<s-General-Q11-20-q-19, Next question -- Q19>>

[[s-General-Q11-20-q-19]]
=== Q19

[big]#General (Q11--20): Question 19#

==== Question

Name the city in which the lead singer of this band is buried.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Doors-Light-My-Fire-cq8k-ZbsXDI.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_8" onclick="toggle_hidden_q1_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_8]]
Paris +
The Doors / The Doors / Light My Fire


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_8");
z.style.display = "none"
function toggle_hidden_q1_8() {
  var x = document.getElementById("answer_q1_8");
  var b = document.getElementById("button_q1_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-18, Previous question -- Q18>> +
<<s-General-Q11-20-q-20, Next question -- Q20>>

[[s-General-Q11-20-q-20]]
=== Q20

[big]#General (Q11--20): Question 20#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Louis-Armstrong-What-A-Wonderful-World-Lyrics-A3yCcXgbKrE.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_9" onclick="toggle_hidden_q1_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_9]]
What a Wonderful World +
Louis Armstrong / Hello Louis - The Hit Years (1963-1969) / What A Wonderful World


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_9");
z.style.display = "none"
function toggle_hidden_q1_9() {
  var x = document.getElementById("answer_q1_9");
  var b = document.getElementById("button_q1_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-19, Previous question -- Q19>> +
<<s-General-Q21-30-q-21, Next question -- General (Q21--30): Q21>>

[[s2]]
== General (Q21--30)

[[s-General-Q21-30-q-21]]
=== Q21

[big]#General (Q21--30): Question 21#

==== Question

Name the performer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Chuck-Berry-Johnny-B.-Goode-Single-tXba00vudss.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_0" onclick="toggle_hidden_q2_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_0]]
Chuck Berry +
Chuck Berry / 20th Century Masters: The Millennium Collection: Best Of Chuck Berry / Johnny B. Goode - Single Version


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_0");
z.style.display = "none"
function toggle_hidden_q2_0() {
  var x = document.getElementById("answer_q2_0");
  var b = document.getElementById("button_q2_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-20, Previous question -- General (Q11--20): Q20>> +
<<s-General-Q21-30-q-22, Next question -- Q22>>

[[s-General-Q21-30-q-22]]
=== Q22

[big]#General (Q21--30): Question 22#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Tequila-The-Champs-3H6amDbAwlY.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_1" onclick="toggle_hidden_q2_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_1]]
The Champs +
The Champs / Tequila / Tequila (Original)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_1");
z.style.display = "none"
function toggle_hidden_q2_1() {
  var x = document.getElementById("answer_q2_1");
  var b = document.getElementById("button_q2_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-21, Previous question -- Q21>> +
<<s-General-Q21-30-q-23, Next question -- Q23>>

[[s-General-Q21-30-q-23]]
=== Q23

[big]#General (Q21--30): Question 23#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Mark-Ronson-Uptown-Funk-Official-Video-ft.-Bruno-Mars-OPf0YbXqDm0.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_2" onclick="toggle_hidden_q2_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_2]]
Uptown Funk +
Mark Ronson, Bruno Mars / Uptown Special / Uptown Funk (feat. Bruno Mars)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_2");
z.style.display = "none"
function toggle_hidden_q2_2() {
  var x = document.getElementById("answer_q2_2");
  var b = document.getElementById("button_q2_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-22, Previous question -- Q22>> +
<<s-General-Q21-30-q-24, Next question -- Q24>>

[[s-General-Q21-30-q-24]]
=== Q24

[big]#General (Q21--30): Question 24#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Lorde-Royals-With-Lyrics-Pure-Heroine-4znHLOWm7pY.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_3" onclick="toggle_hidden_q2_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_3]]
Royals +
Lorde / Pure Heroine / Royals


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_3");
z.style.display = "none"
function toggle_hidden_q2_3() {
  var x = document.getElementById("answer_q2_3");
  var b = document.getElementById("button_q2_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-23, Previous question -- Q23>> +
<<s-General-Q21-30-q-25, Next question -- Q25>>

[[s-General-Q21-30-q-25]]
=== Q25

[big]#General (Q21--30): Question 25#

==== Question

Name the performer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Moondance-2013-Remaster-7kfYOGndVfU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_4" onclick="toggle_hidden_q2_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_4]]
Van Morrison +
Van Morrison / Moondance (Deluxe Edition) / Moondance - 2013 Remaster


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_4");
z.style.display = "none"
function toggle_hidden_q2_4() {
  var x = document.getElementById("answer_q2_4");
  var b = document.getElementById("button_q2_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-24, Previous question -- Q24>> +
<<s-General-Q21-30-q-26, Next question -- Q26>>

[[s-General-Q21-30-q-26]]
=== Q26

[big]#General (Q21--30): Question 26#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Bob-Marley-The-Wailers-Is-This-Love-cOJsK8qbAaA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_5" onclick="toggle_hidden_q2_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_5]]
Is this Love +
Bob Marley & The Wailers / Kaya - Deluxe Edition / Is This Love


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_5");
z.style.display = "none"
function toggle_hidden_q2_5() {
  var x = document.getElementById("answer_q2_5");
  var b = document.getElementById("button_q2_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-25, Previous question -- Q25>> +
<<s-General-Q21-30-q-27, Next question -- Q27>>

[[s-General-Q21-30-q-27]]
=== Q27

[big]#General (Q21--30): Question 27#

==== Question

Name the song. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/My-Generation-Mono-Version-fRipFYoji2A.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_6" onclick="toggle_hidden_q2_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_6]]
My Generation +
The Who / The Who Sings My Generation (U.S. Version) / My Generation - Mono Version


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_6");
z.style.display = "none"
function toggle_hidden_q2_6() {
  var x = document.getElementById("answer_q2_6");
  var b = document.getElementById("button_q2_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-26, Previous question -- Q26>> +
<<s-General-Q21-30-q-28, Next question -- Q28>>

[[s-General-Q21-30-q-28]]
=== Q28

[big]#General (Q21--30): Question 28#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Come-Sail-Away-eYCFrcCqh7Q.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_7" onclick="toggle_hidden_q2_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_7]]
Styx +
Styx / The Grand Illusion / Come Sail Away


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_7");
z.style.display = "none"
function toggle_hidden_q2_7() {
  var x = document.getElementById("answer_q2_7");
  var b = document.getElementById("button_q2_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-27, Previous question -- Q27>> +
<<s-General-Q21-30-q-29, Next question -- Q29>>

[[s-General-Q21-30-q-29]]
=== Q29

[big]#General (Q21--30): Question 29#

==== Question

Name the lead singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Aerosmith-Walk-This-Way-Audio-4c8O2n1Gfto.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_8" onclick="toggle_hidden_q2_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_8]]
Steven Tyler +
Aerosmith / Toys In The Attic / Walk This Way


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_8");
z.style.display = "none"
function toggle_hidden_q2_8() {
  var x = document.getElementById("answer_q2_8");
  var b = document.getElementById("button_q2_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-28, Previous question -- Q28>> +
<<s-General-Q21-30-q-30, Next question -- Q30>>

[[s-General-Q21-30-q-30]]
=== Q30

[big]#General (Q21--30): Question 30#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Free-Bird-CqnU-sJ8V-E.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_9" onclick="toggle_hidden_q2_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_9]]
Free Bird +
Lynyrd Skynyrd / Pronounced' Leh-'Nerd 'Skin-'Nerd / Free Bird


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_9");
z.style.display = "none"
function toggle_hidden_q2_9() {
  var x = document.getElementById("answer_q2_9");
  var b = document.getElementById("button_q2_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-29, Previous question -- Q29>> +
<<s-General-Q31-40-q-31, Next question -- General (Q31--40): Q31>>

[[s3]]
== General (Q31--40)

[[s-General-Q31-40-q-31]]
=== Q31

[big]#General (Q31--40): Question 31#

==== Question

Name the song. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Jimmy-Buffett-Margaritaville-with-lyrics-ue2-ZVxpVjc.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_0" onclick="toggle_hidden_q3_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_0]]
Margaritaville +
Jimmy Buffett / Songs You Know By Heart / Margaritaville


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_0");
z.style.display = "none"
function toggle_hidden_q3_0() {
  var x = document.getElementById("answer_q3_0");
  var b = document.getElementById("button_q3_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-30, Previous question -- General (Q21--30): Q30>> +
<<s-General-Q31-40-q-32, Next question -- Q32>>

[[s-General-Q31-40-q-32]]
=== Q32

[big]#General (Q31--40): Question 32#

==== Question

Name the performer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Eric-Clapton-Cocaine-lyrics-3bEUaeG4wH4.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_1" onclick="toggle_hidden_q3_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_1]]
Eric Clapton +
Eric Clapton / Slowhand 35th Anniversary (Super Deluxe) / Cocaine


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_1");
z.style.display = "none"
function toggle_hidden_q3_1() {
  var x = document.getElementById("answer_q3_1");
  var b = document.getElementById("button_q3_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-31, Previous question -- Q31>> +
<<s-General-Q31-40-q-33, Next question -- Q33>>

[[s-General-Q31-40-q-33]]
=== Q33

[big]#General (Q31--40): Question 33#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Kanye-West-Gold-Digger-ft.-Jamie-Foxx-6vwNcNOTVzY.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_2" onclick="toggle_hidden_q3_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_2]]
Gold Digger +
Kanye West, Jamie Foxx / Late Registration / Gold Digger


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_2");
z.style.display = "none"
function toggle_hidden_q3_2() {
  var x = document.getElementById("answer_q3_2");
  var b = document.getElementById("button_q3_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-32, Previous question -- Q32>> +
<<s-General-Q31-40-q-34, Next question -- Q34>>

[[s-General-Q31-40-q-34]]
=== Q34

[big]#General (Q31--40): Question 34#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Black-Eyed-Peas-I-Gotta-Feeling-Official-Music-Video-uSD4vsh1zDA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_3" onclick="toggle_hidden_q3_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_3]]
Black Eyed Peas +
Black Eyed Peas / THE E.N.D. (THE ENERGY NEVER DIES) / I Gotta Feeling


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_3");
z.style.display = "none"
function toggle_hidden_q3_3() {
  var x = document.getElementById("answer_q3_3");
  var b = document.getElementById("button_q3_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-33, Previous question -- Q33>> +
<<s-General-Q31-40-q-35, Next question -- Q35>>

[[s-General-Q31-40-q-35]]
=== Q35

[big]#General (Q31--40): Question 35#

==== Question

Name the song (including both the main title and the part in parentheses)


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/10.-Rupert-Holmes-Escape-The-Pi-a-Colada-Song-TazHNpt6OTo.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_4" onclick="toggle_hidden_q3_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_4]]
Escape (The Pina Colada Song) +
Rupert Holmes / Partners In Crime / Escape (The Pina Colada Song)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_4");
z.style.display = "none"
function toggle_hidden_q3_4() {
  var x = document.getElementById("answer_q3_4");
  var b = document.getElementById("button_q3_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-34, Previous question -- Q34>> +
<<s-General-Q31-40-q-36, Next question -- Q36>>

[[s-General-Q31-40-q-36]]
=== Q36

[big]#General (Q31--40): Question 36#

==== Question

What does "love" make in this song?


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Ring-of-Fire-Johnny-Cash-mIBTg7q9oNc.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_5" onclick="toggle_hidden_q3_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_5]]
"It makes a fiery ring" +
Johnny Cash / Johnny Cash - 16 Biggest Hits / Ring of Fire


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_5");
z.style.display = "none"
function toggle_hidden_q3_5() {
  var x = document.getElementById("answer_q3_5");
  var b = document.getElementById("button_q3_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-35, Previous question -- Q35>> +
<<s-General-Q31-40-q-37, Next question -- Q37>>

[[s-General-Q31-40-q-37]]
=== Q37

[big]#General (Q31--40): Question 37#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Meghan-Trainor-All-About-That-Bass-Official-Music-Video-7PCkvCPvDXk.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_6" onclick="toggle_hidden_q3_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_6]]
Meghan Trainor +
Meghan Trainor / All About That Bass / All About That Bass


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_6");
z.style.display = "none"
function toggle_hidden_q3_6() {
  var x = document.getElementById("answer_q3_6");
  var b = document.getElementById("button_q3_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-36, Previous question -- Q36>> +
<<s-General-Q31-40-q-38, Next question -- Q38>>

[[s-General-Q31-40-q-38]]
=== Q38

[big]#General (Q31--40): Question 38#

==== Question

Name the song (title must be exact).


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Simon-Garfunkel-Bridge-Over-Troubled-Water-Audio-4G-YQA-bsOU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_7" onclick="toggle_hidden_q3_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_7]]
Bridge Over Troubled Water +
Simon & Garfunkel / Bridge Over Troubled Water / Bridge Over Troubled Water


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_7");
z.style.display = "none"
function toggle_hidden_q3_7() {
  var x = document.getElementById("answer_q3_7");
  var b = document.getElementById("button_q3_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-37, Previous question -- Q37>> +
<<s-General-Q31-40-q-39, Next question -- Q39>>

[[s-General-Q31-40-q-39]]
=== Q39

[big]#General (Q31--40): Question 39#

==== Question

Name the film that this song was featured in. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Pharrell-Williams-Happy-Official-Music-Video-ZbZSe6N-BXs.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_8" onclick="toggle_hidden_q3_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_8]]
Despicable Me 2 +
Pharrell Williams / Despicable Me 2 (Original Motion Picture Soundtrack) / Happy


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_8");
z.style.display = "none"
function toggle_hidden_q3_8() {
  var x = document.getElementById("answer_q3_8");
  var b = document.getElementById("button_q3_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-38, Previous question -- Q38>> +
<<s-General-Q31-40-q-40, Next question -- Q40>>

[[s-General-Q31-40-q-40]]
=== Q40

[big]#General (Q31--40): Question 40#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Go-Your-Own-Way-2004-Remaster-DubafeFeJ7Y.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_9" onclick="toggle_hidden_q3_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_9]]
Go Your Own Way +
Fleetwood Mac / Rumours / Go Your Own Way - 2004 Remaster


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_9");
z.style.display = "none"
function toggle_hidden_q3_9() {
  var x = document.getElementById("answer_q3_9");
  var b = document.getElementById("button_q3_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-39, Previous question -- Q39>> +
<<s-General-Q41-50-q-41, Next question -- General (Q41--50): Q41>>

[[s4]]
== General (Q41--50)

[[s-General-Q41-50-q-41]]
=== Q41

[big]#General (Q41--50): Question 41#

==== Question

Name the group.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/One-Way-Or-Another-Remastered-Fnb1xYDViDs.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_0" onclick="toggle_hidden_q4_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_0]]
Blondie +
Blondie / One Way Or Another / One Way Or Another - Remastered


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_0");
z.style.display = "none"
function toggle_hidden_q4_0() {
  var x = document.getElementById("answer_q4_0");
  var b = document.getElementById("button_q4_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-40, Previous question -- General (Q31--40): Q40>> +
<<s-General-Q41-50-q-42, Next question -- Q42>>

[[s-General-Q41-50-q-42]]
=== Q42

[big]#General (Q41--50): Question 42#

==== Question

Name the group.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Holiday-Boulevard-of-Broken-Dreams-J0xe5DcnYSA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_1" onclick="toggle_hidden_q4_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_1]]
Green Day +
Green Day / American Idiot / Holiday / Boulevard of Broken Dreams


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_1");
z.style.display = "none"
function toggle_hidden_q4_1() {
  var x = document.getElementById("answer_q4_1");
  var b = document.getElementById("button_q4_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-41, Previous question -- Q41>> +
<<s-General-Q41-50-q-43, Next question -- Q43>>

[[s-General-Q41-50-q-43]]
=== Q43

[big]#General (Q41--50): Question 43#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Twist-And-Shout-Remastered-2009-2RicaUqd9Hg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_2" onclick="toggle_hidden_q4_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_2]]
Twist and Shout +
The Beatles / Please Please Me (Remastered) / Twist And Shout - Remastered 2009


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_2");
z.style.display = "none"
function toggle_hidden_q4_2() {
  var x = document.getElementById("answer_q4_2");
  var b = document.getElementById("button_q4_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-42, Previous question -- Q42>> +
<<s-General-Q41-50-q-44, Next question -- Q44>>

[[s-General-Q41-50-q-44]]
=== Q44

[big]#General (Q41--50): Question 44#

==== Question

Name the group.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Isley-Brothers-Shout-rWRsJ-mDU5o.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_3" onclick="toggle_hidden_q4_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_3]]
The Isley Brothers +
The Isley Brothers / Pure... '50s / Shout


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_3");
z.style.display = "none"
function toggle_hidden_q4_3() {
  var x = document.getElementById("answer_q4_3");
  var b = document.getElementById("button_q4_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-43, Previous question -- Q43>> +
<<s-General-Q41-50-q-45, Next question -- Q45>>

[[s-General-Q41-50-q-45]]
=== Q45

[big]#General (Q41--50): Question 45#

==== Question

Name the group.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Build-Me-Up-Buttercup-Nl-2iEP1Wts.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_4" onclick="toggle_hidden_q4_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_4]]
The Foundations +
The Foundations / Build Me Up Buttercup (The Complete Pye Collection) / Build Me Up Buttercup


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_4");
z.style.display = "none"
function toggle_hidden_q4_4() {
  var x = document.getElementById("answer_q4_4");
  var b = document.getElementById("button_q4_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-44, Previous question -- Q44>> +
<<s-General-Q41-50-q-46, Next question -- Q46>>

[[s-General-Q41-50-q-46]]
=== Q46

[big]#General (Q41--50): Question 46#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Wham-Wake-Me-Up-Before-You-Go-Go-Official-HD-Video-ELflyACZXQQ.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_5" onclick="toggle_hidden_q4_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_5]]
Wake Me Up Before You Go-Go +
Wham! / Make It Big / Wake Me Up Before You Go-Go


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_5");
z.style.display = "none"
function toggle_hidden_q4_5() {
  var x = document.getElementById("answer_q4_5");
  var b = document.getElementById("button_q4_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-45, Previous question -- Q45>> +
<<s-General-Q41-50-q-47, Next question -- Q47>>

[[s-General-Q41-50-q-47]]
=== Q47

[big]#General (Q41--50): Question 47#

==== Question

Name the artist.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Elvis-Costello-The-Attractions-Pump-It-Up-3Y71iDvCYXA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_6" onclick="toggle_hidden_q4_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_6]]
Elvis Costello +
Elvis Costello & The Attractions / This Year's Model / Pump It Up


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_6");
z.style.display = "none"
function toggle_hidden_q4_6() {
  var x = document.getElementById("answer_q4_6");
  var b = document.getElementById("button_q4_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-46, Previous question -- Q46>> +
<<s-General-Q41-50-q-48, Next question -- Q48>>

[[s-General-Q41-50-q-48]]
=== Q48

[big]#General (Q41--50): Question 48#

==== Question

Name the album on which this song appeared.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Elvis-Costello-The-Attractions-Everyday-I-Write-The-Book-V1d4r9awjKE.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_7" onclick="toggle_hidden_q4_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_7]]
Punch the Clock +
Elvis Costello & The Attractions / Punch The Clock / Everyday I Write The Book


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_7");
z.style.display = "none"
function toggle_hidden_q4_7() {
  var x = document.getElementById("answer_q4_7");
  var b = document.getElementById("button_q4_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-47, Previous question -- Q47>> +
<<s-General-Q41-50-q-49, Next question -- Q49>>

[[s-General-Q41-50-q-49]]
=== Q49

[big]#General (Q41--50): Question 49#

==== Question

Name the artist.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Marvin-Gaye-What-s-Going-On-H-kA3UtBj4M.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_8" onclick="toggle_hidden_q4_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_8]]
Marvin Gaye +
Marvin Gaye / What's Going On / What's Going On


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_8");
z.style.display = "none"
function toggle_hidden_q4_8() {
  var x = document.getElementById("answer_q4_8");
  var b = document.getElementById("button_q4_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-48, Previous question -- Q48>> +
<<s-General-Q41-50-q-50, Next question -- Q50>>

[[s-General-Q41-50-q-50]]
=== Q50

[big]#General (Q41--50): Question 50#

==== Question

Name the artist.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Theme-From-Shaft-by-Isaac-Hayes-from-Shaft-Music-From-The-Soundtrack-uNJKmf6KTcU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_9" onclick="toggle_hidden_q4_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_9]]
Isaac Hayes +
Isaac Hayes / Shaft (Deluxe Edition) / Theme From Shaft - Album - Remastered


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_9");
z.style.display = "none"
function toggle_hidden_q4_9() {
  var x = document.getElementById("answer_q4_9");
  var b = document.getElementById("button_q4_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-49, Previous question -- Q49>> +
<<s-General-Q51-60-q-51, Next question -- General (Q51--60): Q51>>

[[s5]]
== General (Q51--60)

[[s-General-Q51-60-q-51]]
=== Q51

[big]#General (Q51--60): Question 51#

==== Question

Name the song (inclding both the main title and the part in parentheses).


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Norwegian-Wood-This-Bird-Has-Flown-Y-V6y1ZCg-8.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_0" onclick="toggle_hidden_q5_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_0]]
Norwegian Wood (This Bird Has Flown) +
The Beatles / Rubber Soul (Remastered) / Norwegian Wood (This Bird Has Flown) - Remastered 2009


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_0");
z.style.display = "none"
function toggle_hidden_q5_0() {
  var x = document.getElementById("answer_q5_0");
  var b = document.getElementById("button_q5_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-50, Previous question -- General (Q41--50): Q50>> +
<<s-General-Q51-60-q-52, Next question -- Q52>>

[[s-General-Q51-60-q-52]]
=== Q52

[big]#General (Q51--60): Question 52#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/I-Want-To-Hold-Your-Hand-Remastered-2015-v1HDt1tknTc.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_1" onclick="toggle_hidden_q5_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_1]]
I Want to Hold Your Hand +
The Beatles / 1 (Remastered) / I Want To Hold Your Hand - Remastered 2015


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_1");
z.style.display = "none"
function toggle_hidden_q5_1() {
  var x = document.getElementById("answer_q5_1");
  var b = document.getElementById("button_q5_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-51, Previous question -- Q51>> +
<<s-General-Q51-60-q-53, Next question -- Q53>>

[[s-General-Q51-60-q-53]]
=== Q53

[big]#General (Q51--60): Question 53#

==== Question

Name the song. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Blackbird-Remastered-2009-Man4Xw8Xypo.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_2" onclick="toggle_hidden_q5_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_2]]
Blackbird +
The Beatles / The Beatles (Remastered) / Blackbird - Remastered


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_2");
z.style.display = "none"
function toggle_hidden_q5_2() {
  var x = document.getElementById("answer_q5_2");
  var b = document.getElementById("button_q5_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-52, Previous question -- Q52>> +
<<s-General-Q51-60-q-54, Next question -- Q54>>

[[s-General-Q51-60-q-54]]
=== Q54

[big]#General (Q51--60): Question 54#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/God-Only-Knows-Remastered-CWPo5SC3zik.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_3" onclick="toggle_hidden_q5_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_3]]
God Only Knows +
The Beach Boys / Pet Sounds (Original Mono & Stereo Mix Versions) / God Only Knows - Remastered


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_3");
z.style.display = "none"
function toggle_hidden_q5_3() {
  var x = document.getElementById("answer_q5_3");
  var b = document.getElementById("button_q5_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-53, Previous question -- Q53>> +
<<s-General-Q51-60-q-55, Next question -- Q55>>

[[s-General-Q51-60-q-55]]
=== Q55

[big]#General (Q51--60): Question 55#

==== Question

Name the performer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/JOE-JACKSON-Is-She-Really-Going-Out-with-Him-HD-6TzKSFbsh2Y.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_4" onclick="toggle_hidden_q5_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_4]]
Joe Jackson +
Joe Jackson / Look Sharp! / Is She Really Going Out With Him?


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_4");
z.style.display = "none"
function toggle_hidden_q5_4() {
  var x = document.getElementById("answer_q5_4");
  var b = document.getElementById("button_q5_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-54, Previous question -- Q54>> +
<<s-General-Q51-60-q-56, Next question -- Q56>>

[[s-General-Q51-60-q-56]]
=== Q56

[big]#General (Q51--60): Question 56#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Come-On-Eileen-GbpnAGajyMc.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_5" onclick="toggle_hidden_q5_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_5]]
Dexys Midnight Runners +
Dexys Midnight Runners / Too Rye Ay / Come On Eileen


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_5");
z.style.display = "none"
function toggle_hidden_q5_5() {
  var x = document.getElementById("answer_q5_5");
  var b = document.getElementById("button_q5_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-55, Previous question -- Q55>> +
<<s-General-Q51-60-q-57, Next question -- Q57>>

[[s-General-Q51-60-q-57]]
=== Q57

[big]#General (Q51--60): Question 57#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Logical-Song-low6Coqrw9Y.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_6" onclick="toggle_hidden_q5_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_6]]
The Logical Song +
Supertramp / Breakfast In America (Deluxe Edition) / The Logical Song - Remastered 2010


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_6");
z.style.display = "none"
function toggle_hidden_q5_6() {
  var x = document.getElementById("answer_q5_6");
  var b = document.getElementById("button_q5_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-56, Previous question -- Q56>> +
<<s-General-Q51-60-q-58, Next question -- Q58>>

[[s-General-Q51-60-q-58]]
=== Q58

[big]#General (Q51--60): Question 58#

==== Question

Name the song.   


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Rebel-Rebel-1997-Remaster-Wb3bfsuttdk.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_7" onclick="toggle_hidden_q5_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_7]]
Rebel Rebel +
David Bowie / Best Of Bowie / Rebel Rebel - 1999 Digital Remaster


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_7");
z.style.display = "none"
function toggle_hidden_q5_7() {
  var x = document.getElementById("answer_q5_7");
  var b = document.getElementById("button_q5_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-57, Previous question -- Q57>> +
<<s-General-Q51-60-q-59, Next question -- Q59>>

[[s-General-Q51-60-q-59]]
=== Q59

[big]#General (Q51--60): Question 59#

==== Question

Name the album on which this song appeared.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Kendrick-Lamar-King-Kunta-hRK7PVJFbS8.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_8" onclick="toggle_hidden_q5_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_8]]
To Pimp a Butterfly +
Kendrick Lamar / To Pimp A Butterfly / King Kunta


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_8");
z.style.display = "none"
function toggle_hidden_q5_8() {
  var x = document.getElementById("answer_q5_8");
  var b = document.getElementById("button_q5_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-58, Previous question -- Q58>> +
<<s-General-Q51-60-q-60, Next question -- Q60>>

[[s-General-Q51-60-q-60]]
=== Q60

[big]#General (Q51--60): Question 60#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/01-Bruno-Mars-Grenade-Doo-Wops-Hooligans-aLAtJ0k98SI.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_9" onclick="toggle_hidden_q5_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_9]]
Grenade +
Bruno Mars / Doo-Wops & Hooligans / Grenade


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_9");
z.style.display = "none"
function toggle_hidden_q5_9() {
  var x = document.getElementById("answer_q5_9");
  var b = document.getElementById("button_q5_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-59, Previous question -- Q59>> +
<<s-One-Hit-Wonders-q-1, Next question -- One Hit Wonders: Q1>>

[[s6]]
== One Hit Wonders

[[s-One-Hit-Wonders-q-1]]
=== Q1

[big]#One Hit Wonders: Question 1#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Men-Without-Hats-Safety-Dance-Official-Music-Video-AjPau5QYtYs.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_0" onclick="toggle_hidden_q6_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_0]]
Men Without Hats +
Men Without Hats / Greatest / The Safety Dance


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_0");
z.style.display = "none"
function toggle_hidden_q6_0() {
  var x = document.getElementById("answer_q6_0");
  var b = document.getElementById("button_q6_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-60, Previous question -- General (Q51--60): Q60>> +
<<s-One-Hit-Wonders-q-2, Next question -- Q2>>

[[s-One-Hit-Wonders-q-2]]
=== Q2

[big]#One Hit Wonders: Question 2#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Spirit-In-The-Sky-Norman-Greenbaum-AZQxH-8raCI.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_1" onclick="toggle_hidden_q6_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_1]]
Norman Greenbaum +
Norman Greenbaum / Spirit In The Sky / Spirit In The Sky


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_1");
z.style.display = "none"
function toggle_hidden_q6_1() {
  var x = document.getElementById("answer_q6_1");
  var b = document.getElementById("button_q6_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-1, Previous question -- Q1>> +
<<s-One-Hit-Wonders-q-3, Next question -- Q3>>

[[s-One-Hit-Wonders-q-3]]
=== Q3

[big]#One Hit Wonders: Question 3#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Bobby-McFerrin-Don-t-Worry-Be-Happy-Official-Video-d-diB65scQU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_2" onclick="toggle_hidden_q6_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_2]]
Bobby McFerrin +
Bobby McFerrin / 20 #1's: One Hit Wonders / Don't Worry Be Happy


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_2");
z.style.display = "none"
function toggle_hidden_q6_2() {
  var x = document.getElementById("answer_q6_2");
  var b = document.getElementById("button_q6_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-2, Previous question -- Q2>> +
<<s-One-Hit-Wonders-q-4, Next question -- Q4>>

[[s-One-Hit-Wonders-q-4]]
=== Q4

[big]#One Hit Wonders: Question 4#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Rockwell-Somebody-s-Watching-Me-Official-Video-7YvAYIJSSZY.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_3" onclick="toggle_hidden_q6_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_3]]
Rockwell +
Rockwell / 20 #1's: One Hit Wonders / Somebody's Watching Me - Single Version


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_3");
z.style.display = "none"
function toggle_hidden_q6_3() {
  var x = document.getElementById("answer_q6_3");
  var b = document.getElementById("button_q6_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-3, Previous question -- Q3>> +
<<s-One-Hit-Wonders-q-5, Next question -- Q5>>

[[s-One-Hit-Wonders-q-5]]
=== Q5

[big]#One Hit Wonders: Question 5#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Bruce-Channel-Hey-Baby-ik9dxkKriV0.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_4" onclick="toggle_hidden_q6_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_4]]
Bruce Channel +
Bruce Channel / 20 #1's: One Hit Wonders / Hey! Baby


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_4");
z.style.display = "none"
function toggle_hidden_q6_4() {
  var x = document.getElementById("answer_q6_4");
  var b = document.getElementById("button_q6_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-4, Previous question -- Q4>> +
<<s-One-Hit-Wonders-q-6, Next question -- Q6>>

[[s-One-Hit-Wonders-q-6]]
=== Q6

[big]#One Hit Wonders: Question 6#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Ready-For-The-World-Oh-Sheila-Official-Video-wbL2lMn34Oo.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_5" onclick="toggle_hidden_q6_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_5]]
Ready for the World. +
Ready For The World / 20 #1's: One Hit Wonders / Oh Sheila


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_5");
z.style.display = "none"
function toggle_hidden_q6_5() {
  var x = document.getElementById("answer_q6_5");
  var b = document.getElementById("button_q6_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-5, Previous question -- Q5>> +
<<s-One-Hit-Wonders-q-7, Next question -- Q7>>

[[s-One-Hit-Wonders-q-7]]
=== Q7

[big]#One Hit Wonders: Question 7#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Quarterflash-Harden-My-Heart-Official-Video-OqeKV2UYq1Q.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_6" onclick="toggle_hidden_q6_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_6]]
Quarterflash +
Quarterflash / 20 #1's: One Hit Wonders / Harden My Heart


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_6");
z.style.display = "none"
function toggle_hidden_q6_6() {
  var x = document.getElementById("answer_q6_6");
  var b = document.getElementById("button_q6_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-6, Previous question -- Q6>> +
<<s-One-Hit-Wonders-q-8, Next question -- Q8>>

[[s-One-Hit-Wonders-q-8]]
=== Q8

[big]#One Hit Wonders: Question 8#

==== Question

Name the band.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Knack-My-Sharona-1979-BR2JtsVumFA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_7" onclick="toggle_hidden_q6_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_7]]
The Knack +
The Knack / 20 #1's: One Hit Wonders / My Sharona


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_7");
z.style.display = "none"
function toggle_hidden_q6_7() {
  var x = document.getElementById("answer_q6_7");
  var b = document.getElementById("button_q6_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-7, Previous question -- Q7>> +
<<s-One-Hit-Wonders-q-9, Next question -- Q9>>

[[s-One-Hit-Wonders-q-9]]
=== Q9

[big]#One Hit Wonders: Question 9#

==== Question

Name the band with the very 70s-sounding name.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/disco-duck-97RjuC9YeXg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_8" onclick="toggle_hidden_q6_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_8]]
The Rubix Cubes +
The Rubix Cube's / 1970's One Hit Wonders / Disco Duck


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_8");
z.style.display = "none"
function toggle_hidden_q6_8() {
  var x = document.getElementById("answer_q6_8");
  var b = document.getElementById("button_q6_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-8, Previous question -- Q8>> +
<<s-One-Hit-Wonders-q-10, Next question -- Q10>>

[[s-One-Hit-Wonders-q-10]]
=== Q10

[big]#One Hit Wonders: Question 10#

==== Question

Name the singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Bette-Davis-Eyes-Re-Recorded-Remastered-tDJdEhbSP-g.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_9" onclick="toggle_hidden_q6_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_9]]
Kim Carnes +
Kim Carnes / 80s 1 Hit Wonders (Re-Recorded / Remastered Versions) / Bette Davis Eyes (Re-Recorded / Remastered)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_9");
z.style.display = "none"
function toggle_hidden_q6_9() {
  var x = document.getElementById("answer_q6_9");
  var b = document.getElementById("button_q6_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-9, Previous question -- Q9>> +
<<s-Movie-q-1, Next question -- Movie: Q1>>

[[s7]]
== Movie

[[s-Movie-q-1]]
=== Q1

[big]#Movie: Question 1#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Jules-and-Jim-Movie-Main-Theme-iFtFCZhFnMU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_0" onclick="toggle_hidden_q7_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_0]]
Jules and Jim +
Film & TV Masters / Ultimate Movie Theme Playlist / Jules and Jim (Movie Main Theme)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_0");
z.style.display = "none"
function toggle_hidden_q7_0() {
  var x = document.getElementById("answer_q7_0");
  var b = document.getElementById("button_q7_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-One-Hit-Wonders-q-10, Previous question -- One Hit Wonders: Q10>> +
<<s-Movie-q-2, Next question -- Q2>>

[[s-Movie-q-2]]
=== Q2

[big]#Movie: Question 2#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Good-the-Bad-and-the-Ugly-Movie-Main-Theme-o-zafpeLXhE.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_1" onclick="toggle_hidden_q7_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_1]]
The Good, the Bad and the Ugly +
Film & TV Masters / Ultimate Movie Theme Playlist / The Good, the Bad and the Ugly (Movie Main Theme)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_1");
z.style.display = "none"
function toggle_hidden_q7_1() {
  var x = document.getElementById("answer_q7_1");
  var b = document.getElementById("button_q7_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-1, Previous question -- Q1>> +
<<s-Movie-q-3, Next question -- Q3>>

[[s-Movie-q-3]]
=== Q3

[big]#Movie: Question 3#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Superman-Movie-Main-Theme-cm97g2cOKto.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_2" onclick="toggle_hidden_q7_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_2]]
Superman +
Film & TV Masters / Ultimate Movie Theme Playlist / Superman (Movie Main Theme)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_2");
z.style.display = "none"
function toggle_hidden_q7_2() {
  var x = document.getElementById("answer_q7_2");
  var b = document.getElementById("button_q7_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-2, Previous question -- Q2>> +
<<s-Movie-q-4, Next question -- Q4>>

[[s-Movie-q-4]]
=== Q4

[big]#Movie: Question 4#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/A-Man-and-a-Woman-Movie-Main-Theme-So9rDiGxQTQ.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_3" onclick="toggle_hidden_q7_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_3]]
A man and a Woman +
Film & TV Masters / Ultimate Movie Theme Playlist / A Man and a Woman (Movie Main Theme)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_3");
z.style.display = "none"
function toggle_hidden_q7_3() {
  var x = document.getElementById("answer_q7_3");
  var b = document.getElementById("button_q7_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-3, Previous question -- Q3>> +
<<s-Movie-q-5, Next question -- Q5>>

[[s-Movie-q-5]]
=== Q5

[big]#Movie: Question 5#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Godfather-DGtEtwdZZKo.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_4" onclick="toggle_hidden_q7_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_4]]
The Godfather. +
A Century Of Movie Soundtracks / A Century Of Movie Soundtracks Vol. 2 / The Godfather


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_4");
z.style.display = "none"
function toggle_hidden_q7_4() {
  var x = document.getElementById("answer_q7_4");
  var b = document.getElementById("button_q7_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-4, Previous question -- Q4>> +
<<s-Movie-q-6, Next question -- Q6>>

[[s-Movie-q-6]]
=== Q6

[big]#Movie: Question 6#

==== Question

Name the composer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Pink-Panther-XdnnytXfj5g.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_5" onclick="toggle_hidden_q7_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_5]]
Henry Mancini +
A Century Of Movie Soundtracks / A Century Of Movie Soundtracks Vol. 1 / The Pink Panther


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_5");
z.style.display = "none"
function toggle_hidden_q7_5() {
  var x = document.getElementById("answer_q7_5");
  var b = document.getElementById("button_q7_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-5, Previous question -- Q5>> +
<<s-Movie-q-7, Next question -- Q7>>

[[s-Movie-q-7]]
=== Q7

[big]#Movie: Question 7#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/End-Title-O-6Da8wD0A.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_6" onclick="toggle_hidden_q7_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_6]]
Lawrence of Arabia +
London Philharmonic Orchestra / Lawrence Of Arabia (Original Soundtrack Recording) / End Title (from "Lawrence Of Arabia")


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_6");
z.style.display = "none"
function toggle_hidden_q7_6() {
  var x = document.getElementById("answer_q7_6");
  var b = document.getElementById("button_q7_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-6, Previous question -- Q6>> +
<<s-Movie-q-8, Next question -- Q8>>

[[s-Movie-q-8]]
=== Q8

[big]#Movie: Question 8#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/La-dolce-vita-Titoli-testa-Canzonetta-Notturno-Cadillac-M-pDPlITpcU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_7" onclick="toggle_hidden_q7_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_7]]
La Dolce Vita +
Nino Rota, Studio Orchestra, StudioConductor / Original Music for the Movies of Federico Fellini / La dolce vita


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_7");
z.style.display = "none"
function toggle_hidden_q7_7() {
  var x = document.getElementById("answer_q7_7");
  var b = document.getElementById("button_q7_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-7, Previous question -- Q7>> +
<<s-Movie-q-9, Next question -- Q9>>

[[s-Movie-q-9]]
=== Q9

[big]#Movie: Question 9#

==== Question

Name the composer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Nino-Rota-Amarcord-bk4MEhUkxco.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_8" onclick="toggle_hidden_q7_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_8]]
Nino Rota +
Nino Rota / Amarcord / Amarcord


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_8");
z.style.display = "none"
function toggle_hidden_q7_8() {
  var x = document.getElementById("answer_q7_8");
  var b = document.getElementById("button_q7_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-8, Previous question -- Q8>> +
<<s-Movie-q-10, Next question -- Q10>>

[[s-Movie-q-10]]
=== Q10

[big]#Movie: Question 10#

==== Question

Name the movie.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Patton-March-HAe40MzBktg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_9" onclick="toggle_hidden_q7_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_9]]
Patton +
DLG Orchestra / Greatest Movie Themes / Patton


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_9");
z.style.display = "none"
function toggle_hidden_q7_9() {
  var x = document.getElementById("answer_q7_9");
  var b = document.getElementById("button_q7_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-9, Previous question -- Q9>> +
<<s-Broadway-q-1, Next question -- Broadway: Q1>>

[[s8]]
== Broadway

[[s-Broadway-q-1]]
=== Q1

[big]#Broadway: Question 1#

==== Question

Name the composer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Being-Alive-Company-2006-Broadway-Revival-Raul-Esparza-YLTulpBF3H4.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_0" onclick="toggle_hidden_q8_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_0]]
Stephen Sondheim +
2006 Broadway Revival Cast / Company (2006 Broadway Revival Cast) / Being Alive


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_0");
z.style.display = "none"
function toggle_hidden_q8_0() {
  var x = document.getElementById("answer_q8_0");
  var b = document.getElementById("button_q8_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Movie-q-10, Previous question -- Movie: Q10>> +
<<s-Broadway-q-2, Next question -- Q2>>

[[s-Broadway-q-2]]
=== Q2

[big]#Broadway: Question 2#

==== Question

Name the musical.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Whatever-Lola-Wants-Damn-Yankees.-6kjQmgm0r4g.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_1" onclick="toggle_hidden_q8_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_1]]
Damn Yankees +
Gwen Verdon / Damn Yankees (Original Soundtrack) [Remastered] / Whatever Lola Wants


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_1");
z.style.display = "none"
function toggle_hidden_q8_1() {
  var x = document.getElementById("answer_q8_1");
  var b = document.getElementById("button_q8_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-1, Previous question -- Q1>> +
<<s-Broadway-q-3, Next question -- Q3>>

[[s-Broadway-q-3]]
=== Q3

[big]#Broadway: Question 3#

==== Question

Name the composer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Annie-Get-Your-Gun-1999-Broadway-Revival-Cast-9.-They-Say-It-s-Wonderful-3nuUHCKiBuo.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_2" onclick="toggle_hidden_q8_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_2]]
Irving Berlin +
Annie Get Your Gun - The 1999 Broadway Cast / Annie Get Your Gun - The New Broadway Cast Recording (Staring Bernadette Peters) / They Say It's Wonderful


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_2");
z.style.display = "none"
function toggle_hidden_q8_2() {
  var x = document.getElementById("answer_q8_2");
  var b = document.getElementById("button_q8_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-2, Previous question -- Q2>> +
<<s-Broadway-q-4, Next question -- Q4>>

[[s-Broadway-q-4]]
=== Q4

[big]#Broadway: Question 4#

==== Question

Name the musical.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Alexander-Hamilton-VhinPd5RRJw.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_3" onclick="toggle_hidden_q8_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_3]]
Hamilton +
Leslie Odom, Jr., Anthony Ramos, Daveed Diggs, Okieriete Onaodowan, Lin-Manuel Miranda, Phillipa Soo, Christopher Jackson & Original Broadway Cast of Hamilton / Hamilton (Original Broadway Cast Recording) / Alexander Hamilton


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_3");
z.style.display = "none"
function toggle_hidden_q8_3() {
  var x = document.getElementById("answer_q8_3");
  var b = document.getElementById("button_q8_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-3, Previous question -- Q3>> +
<<s-Broadway-q-5, Next question -- Q5>>

[[s-Broadway-q-5]]
=== Q5

[big]#Broadway: Question 5#

==== Question

Name the musical.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/One-Reprise-Finale-OiBIXa-7Vo.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_4" onclick="toggle_hidden_q8_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_4]]
A Chorus Line +
A Chorus Line Ensemble / A Chorus Line - 40th Anniversary Celebration (Original Broadway Cast Recording) / One (Reprise) / Finale


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_4");
z.style.display = "none"
function toggle_hidden_q8_4() {
  var x = document.getElementById("answer_q8_4");
  var b = document.getElementById("button_q8_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-4, Previous question -- Q4>> +
<<s-Broadway-q-6, Next question -- Q6>>

[[s-Broadway-q-6]]
=== Q6

[big]#Broadway: Question 6#

==== Question

Name the song. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Barbra-Streisand-Don-t-Rain-On-My-Parade-oZTSuMErgsw.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_5" onclick="toggle_hidden_q8_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_5]]
Don't Rain On My Parade +
Barbra Streisand / The Essential Barbra Streisand / Don't Rain On My Parade


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_5");
z.style.display = "none"
function toggle_hidden_q8_5() {
  var x = document.getElementById("answer_q8_5");
  var b = document.getElementById("button_q8_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-5, Previous question -- Q5>> +
<<s-Broadway-q-7, Next question -- Q7>>

[[s-Broadway-q-7]]
=== Q7

[big]#Broadway: Question 7#

==== Question

Name the musical.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Corner-of-the-Sky-Mdkyc686VIg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_6" onclick="toggle_hidden_q8_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_6]]
Pippin +
Matthew James Thomas / Pippin (New Broadway Cast Recording) / Corner of the Sky


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_6");
z.style.display = "none"
function toggle_hidden_q8_6() {
  var x = document.getElementById("answer_q8_6");
  var b = document.getElementById("button_q8_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-6, Previous question -- Q6>> +
<<s-Broadway-q-8, Next question -- Q8>>

[[s-Broadway-q-8]]
=== Q8

[big]#Broadway: Question 8#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/West-Side-Story-Something-s-Coming-1961-HD-FOQPMjKLQQU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_7" onclick="toggle_hidden_q8_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_7]]
Something's Coming. +
Matt Cavenaugh / West Side Story (New Broadway Cast Recording - 2009) / Something's Coming


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_7");
z.style.display = "none"
function toggle_hidden_q8_7() {
  var x = document.getElementById("answer_q8_7");
  var b = document.getElementById("button_q8_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-7, Previous question -- Q7>> +
<<s-Broadway-q-9, Next question -- Q9>>

[[s-Broadway-q-9]]
=== Q9

[big]#Broadway: Question 9#

==== Question

Name the musical.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Overture-Te-Tgsw2vOE.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_8" onclick="toggle_hidden_q8_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_8]]
Gypsy +
2003 Broadway Cast of "Gypsy" / Gypsy (2003 Broadway Cast) / Overture


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_8");
z.style.display = "none"
function toggle_hidden_q8_8() {
  var x = document.getElementById("answer_q8_8");
  var b = document.getElementById("button_q8_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-8, Previous question -- Q8>> +
<<s-Broadway-q-10, Next question -- Q10>>

[[s-Broadway-q-10]]
=== Q10

[big]#Broadway: Question 10#

==== Question

Name the musical.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/42nd-Street-bPuQkW1-s9k.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_9" onclick="toggle_hidden_q8_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_9]]
42nd Street +
Wanda Richert, Lee Roy Reams & 42nd Street Ensemble / 42nd Street - Original Broadway Cast Recording / 42nd Street


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_9");
z.style.display = "none"
function toggle_hidden_q8_9() {
  var x = document.getElementById("answer_q8_9");
  var b = document.getElementById("button_q8_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-9, Previous question -- Q9>> +
<<s-New-York-q-1, Next question -- New York: Q1>>

[[s9]]
== New York

[[s-New-York-q-1]]
=== Q1

[big]#New York: Question 1#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Bruce-Springsteen-Tenth-Avenue-Freeze-Out.wmv-BL-HL3ELvFI.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_0" onclick="toggle_hidden_q9_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_0]]
Tenth Avenue Freeze Out +
Bruce Springsteen / Born To Run / Tenth Avenue Freeze-Out


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_0");
z.style.display = "none"
function toggle_hidden_q9_0() {
  var x = document.getElementById("answer_q9_0");
  var b = document.getElementById("button_q9_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-10, Previous question -- Broadway: Q10>> +
<<s-New-York-q-2, Next question -- Q2>>

[[s-New-York-q-2]]
=== Q2

[big]#New York: Question 2#

==== Question

Name the person who sang this song in the movie in which it first appeared.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Theme-From-New-York-New-York-Remastered-2008-le1QF3uoQNg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_1" onclick="toggle_hidden_q9_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_1]]
Liza Minelli +
Frank Sinatra / Ultimate Sinatra: The Centennial Collection / Theme from New York, New York


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_1");
z.style.display = "none"
function toggle_hidden_q9_1() {
  var x = document.getElementById("answer_q9_1");
  var b = document.getElementById("button_q9_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-1, Previous question -- Q1>> +
<<s-New-York-q-3, Next question -- Q3>>

[[s-New-York-q-3]]
=== Q3

[big]#New York: Question 3#

==== Question

Name the song. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/GEORGE-BENSON-On-Broadway-Album-Version-ok-l1Acuwg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_2" onclick="toggle_hidden_q9_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_2]]
On Broadway +
George Benson / The George Benson Collection / On Broadway


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_2");
z.style.display = "none"
function toggle_hidden_q9_2() {
  var x = document.getElementById("answer_q9_2");
  var b = document.getElementById("button_q9_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-2, Previous question -- Q2>> +
<<s-New-York-q-4, Next question -- Q4>>

[[s-New-York-q-4]]
=== Q4

[big]#New York: Question 4#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/RUN-DMC-Christmas-In-Hollis-Video-OR07r0ZMFb8.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_3" onclick="toggle_hidden_q9_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_3]]
Christmas in Hollis +
Run-DMC / Tougher Than Leather / Christmas In Hollis (Bonus Track)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_3");
z.style.display = "none"
function toggle_hidden_q9_3() {
  var x = document.getElementById("answer_q9_3");
  var b = document.getElementById("button_q9_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-3, Previous question -- Q3>> +
<<s-New-York-q-5, Next question -- Q5>>

[[s-New-York-q-5]]
=== Q5

[big]#New York: Question 5#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Odyssey-Native-New-Yorker-1977-HD-JpQ6NtbZxiE.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_4" onclick="toggle_hidden_q9_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_4]]
Native New Yorker +
Odyssey / Odyssey (Expanded Edition) / Native New Yorker


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_4");
z.style.display = "none"
function toggle_hidden_q9_4() {
  var x = document.getElementById("answer_q9_4");
  var b = document.getElementById("button_q9_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-4, Previous question -- Q4>> +
<<s-New-York-q-6, Next question -- Q6>>

[[s-New-York-q-6]]
=== Q6

[big]#New York: Question 6#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Jay-Z-feat.-Alicia-Keys-Empire-State-of-Mind-Official-Music-Video-Original-Version-QsZlY0Vz4-o.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_5" onclick="toggle_hidden_q9_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_5]]
Empire State of Mind +
JAY-Z & Alicia Keys / The Hits Collection, Vol. One (Deluxe Edition) / Empire State of Mind (feat. Alicia Keys)


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_5");
z.style.display = "none"
function toggle_hidden_q9_5() {
  var x = document.getElementById("answer_q9_5");
  var b = document.getElementById("button_q9_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-5, Previous question -- Q5>> +
<<s-New-York-q-7, Next question -- Q7>>

[[s-New-York-q-7]]
=== Q7

[big]#New York: Question 7#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Pogues-Fairytale-Of-New-York-Official-Video-j9jbdgZidu8.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_6" onclick="toggle_hidden_q9_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_6]]
Fairytale of New York +
The Pogues / If I Should Fall from Grace With God [Expanded] / Fairytale of New York


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_6");
z.style.display = "none"
function toggle_hidden_q9_6() {
  var x = document.getElementById("answer_q9_6");
  var b = document.getElementById("button_q9_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-6, Previous question -- Q6>> +
<<s-New-York-q-8, Next question -- Q8>>

[[s-New-York-q-8]]
=== Q8

[big]#New York: Question 8#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Ben-E-King-Spanish-Harlem-OGd6CdtOqEE.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_7" onclick="toggle_hidden_q9_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_7]]
Spanish Herlem +
Ben E. King / Spanish Harlem / Spanish Harlem


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_7");
z.style.display = "none"
function toggle_hidden_q9_7() {
  var x = document.getElementById("answer_q9_7");
  var b = document.getElementById("button_q9_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-7, Previous question -- Q7>> +
<<s-New-York-q-9, Next question -- Q9>>

[[s-New-York-q-9]]
=== Q9

[big]#New York: Question 9#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/The-Ad-Libs-The-Boy-From-New-York-City-with-lyrics-3TPYmeSqLjc.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_8" onclick="toggle_hidden_q9_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_8]]
The Boy from New York City +
The Ad Libs / Discover 60s One Hit Wonders / The Boy from New York City


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_8");
z.style.display = "none"
function toggle_hidden_q9_8() {
  var x = document.getElementById("answer_q9_8");
  var b = document.getElementById("button_q9_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-8, Previous question -- Q8>> +
<<s-New-York-q-10, Next question -- Q10>>

[[s-New-York-q-10]]
=== Q10

[big]#New York: Question 10#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Lullaby-Of-Broadway-Live-n8sd4KiP5iA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q9_9" onclick="toggle_hidden_q9_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q9_9]]
Lullaby of Broadway +
Tony Bennett / The White House Sessions, Live 1962 / Lullaby of Broadway (with The Dave Brubeck Trio) [Live]


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q9_9");
z.style.display = "none"
function toggle_hidden_q9_9() {
  var x = document.getElementById("answer_q9_9");
  var b = document.getElementById("button_q9_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-9, Previous question -- Q9>> +
<<s-Bonus-q-1, Next question -- Bonus: Q1>>

[[s10]]
== Bonus

[[s-Bonus-q-1]]
=== Q1

[big]#Bonus: Question 1#

==== Question

In this song, what "has bitten the dust?"


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/London-Calling-Remastered-XN7iEFVLf5c.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_0" onclick="toggle_hidden_q10_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_0]]
Phony Beatlemania +
The Clash / London Calling (Remastered) / London Calling - Remastered


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_0");
z.style.display = "none"
function toggle_hidden_q10_0() {
  var x = document.getElementById("answer_q10_0");
  var b = document.getElementById("button_q10_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-New-York-q-10, Previous question -- New York: Q10>> +
<<s-Bonus-q-2, Next question -- Q2>>

[[s-Bonus-q-2]]
=== Q2

[big]#Bonus: Question 2#

==== Question

Name the group.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Surf-City-Remastered-1990-Stereo-Remix-ZWMcoxeXKAg.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_1" onclick="toggle_hidden_q10_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_1]]
Jan & Dean +
Jan & Dean / Surf City: The Best Of Jan & Dean / Surf City - Remastered 1990/Stereo Remix


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_1");
z.style.display = "none"
function toggle_hidden_q10_1() {
  var x = document.getElementById("answer_q10_1");
  var b = document.getElementById("button_q10_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-1, Previous question -- Q1>> +
<<s-Bonus-q-3, Next question -- Q3>>

[[s-Bonus-q-3]]
=== Q3

[big]#Bonus: Question 3#

==== Question

Name the album.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Joe-Jackson-Look-Sharp-V8-b9LK1trE.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_2" onclick="toggle_hidden_q10_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_2]]
Look Sharp! +
Joe Jackson / Look Sharp! / Look Sharp!


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_2");
z.style.display = "none"
function toggle_hidden_q10_2() {
  var x = document.getElementById("answer_q10_2");
  var b = document.getElementById("button_q10_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-2, Previous question -- Q2>> +
<<s-Bonus-q-4, Next question -- Q4>>

[[s-Bonus-q-4]]
=== Q4

[big]#Bonus: Question 4#

==== Question

Name the movie in which this song was sung by this artist.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Elvis-Presley-Can-t-Help-Falling-In-Love-Audio-vGJTaP6anOU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_3" onclick="toggle_hidden_q10_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_3]]
Blue Hawaii +
Elvis Presley / Blue Hawaii / Can't Help Falling in Love


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_3");
z.style.display = "none"
function toggle_hidden_q10_3() {
  var x = document.getElementById("answer_q10_3");
  var b = document.getElementById("button_q10_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-3, Previous question -- Q3>> +
<<s-Bonus-q-5, Next question -- Q5>>

[[s-Bonus-q-5]]
=== Q5

[big]#Bonus: Question 5#

==== Question

Name the movie in which this song played a significant part,


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Roy-Orbison-In-Dreams-MVRunwyoTMA.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_4" onclick="toggle_hidden_q10_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_4]]
Blue Velvet +
Roy Orbison / In Dreams / In Dreams


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_4");
z.style.display = "none"
function toggle_hidden_q10_4() {
  var x = document.getElementById("answer_q10_4");
  var b = document.getElementById("button_q10_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-4, Previous question -- Q4>> +
<<s-Bonus-q-6, Next question -- Q6>>

[[s-Bonus-q-6]]
=== Q6

[big]#Bonus: Question 6#

==== Question

Name the two movies that had this song as their opening credit music. 


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Rock-Around-the-Clock-Bill-Haley-original-song-1955-Ud-JZcC0tHI.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_5" onclick="toggle_hidden_q10_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_5]]
American Graffiti and Blackboard Jungle +
Bill Haley & His Comets / From The Original Master Tapes / (We're Gonna) Rock Around The Clock - Single Version


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_5");
z.style.display = "none"
function toggle_hidden_q10_5() {
  var x = document.getElementById("answer_q10_5");
  var b = document.getElementById("button_q10_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-5, Previous question -- Q5>> +
<<s-Bonus-q-7, Next question -- Q7>>

[[s-Bonus-q-7]]
=== Q7

[big]#Bonus: Question 7#

==== Question

Name  famous  film in which this song was sung spontaneously.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Hommage-national-la-Marseillaise-du-Choeur-de-l-Arm-e-fran-aise-SLe6KcssqiM.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_6" onclick="toggle_hidden_q10_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_6]]
Casablanca +
Choeur de l'Armée Française, Musique De La Garde Républicaine / Les hymnes officiels de la Coupe du Monde de Rugby (National Anthems Rugby World Cup France) / France: La Marseillaise


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_6");
z.style.display = "none"
function toggle_hidden_q10_6() {
  var x = document.getElementById("answer_q10_6");
  var b = document.getElementById("button_q10_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-6, Previous question -- Q6>> +
<<s-Bonus-q-8, Next question -- Q8>>

[[s-Bonus-q-8]]
=== Q8

[big]#Bonus: Question 8#

==== Question

Name the song.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Carl-Perkins-Gone-Gone-Gone-yrhZKavICNU.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_7" onclick="toggle_hidden_q10_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_7]]
Gone Gone Gone +
Carl Perkins / The Dance Album / Gone, Gone, Gone


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_7");
z.style.display = "none"
function toggle_hidden_q10_7() {
  var x = document.getElementById("answer_q10_7");
  var b = document.getElementById("button_q10_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-7, Previous question -- Q7>> +
<<s-Bonus-q-9, Next question -- Q9>>

[[s-Bonus-q-9]]
=== Q9

[big]#Bonus: Question 9#

==== Question

Name the famous televangelist who was a cousin of the this singer.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Great-Balls-of-Fire-Jerry-Lee-Lewis-original-song-1957-Jt0mg8Z09SY.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_8" onclick="toggle_hidden_q10_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_8]]
Jimmy Swaggert +
Jerry Lee Lewis / The Golden Rock Hits Of Jerry Lee Lewis / Great Balls Of Fire


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_8");
z.style.display = "none"
function toggle_hidden_q10_8() {
  var x = document.getElementById("answer_q10_8");
  var b = document.getElementById("button_q10_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-8, Previous question -- Q8>> +
<<s-Bonus-q-10, Next question -- Q10>>

[[s-Bonus-q-10]]
=== Q10

[big]#Bonus: Question 10#

==== Question

Name the band, the song and the album - we need all three.


+++++++++++
<video
loading="lazy"
controls
width="300
poster="question_mark.jpg"
preload="auto"
playsinline
>
    <source src=Audio/Trimmed/Pet-Sounds-Remastered-EeN-NytxKEc.mp4 type="video/mp4"/>
</video>
+++++++++++


==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q10_9" onclick="toggle_hidden_q10_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q10_9]]
the Beach Boys; Pet Sounds; Pet Sounds +
The Beach Boys / Pet Sounds (Original Mono & Stereo Mix Versions) / Pet Sounds - Remastered


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q10_9");
z.style.display = "none"
function toggle_hidden_q10_9() {
  var x = document.getElementById("answer_q10_9");
  var b = document.getElementById("button_q10_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-9, Previous question -- Q9>>
