
= Music trivia
:toc2:
:toclevels: 2
:toc-title: Welcome to Quarantine Music Trivia!

[subs=""]
++++++++++++
<style>
html, body { height: 100%; }
.fullheight { overflow-y:auto; height:100vh; }​
a { color:blue; }
a:visited { color:blue; }
a:active { color:blue; }
a[tabindex]:focus { color:blue; outline:none; }
</style>
++++++++++++

== Welcome
    

[[s0]]
== General (Q1--10)

[[s-General-Q1-10-q-1]]
=== Q1

[big]#General (Q1--10): Question 1#

==== Question

Qae994

video::LaTeX/Audio/Trimmed/Toto-Africa-Official-Music-Video-FTQbiNvZqaY.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_0" onclick="toggle_hidden_q0_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_0]]
Aae994
LaTeX/Audio/Trimmed/Toto-Africa-Official-Music-Video-FTQbiNvZqaY.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_0");
z.style.display = "none"
function toggle_hidden_q0_0() {
  var x = document.getElementById("answer_q0_0");
  var b = document.getElementById("button_q0_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-2, Next question -- Q2>>

[[s-General-Q1-10-q-2]]
=== Q2

[big]#General (Q1--10): Question 2#

==== Question

Qb3747

video::LaTeX/Audio/Trimmed/Meghan-Trainor-All-About-That-Bass-Official-Music-Video-7PCkvCPvDXk.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_1" onclick="toggle_hidden_q0_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_1]]
Ab3747
LaTeX/Audio/Trimmed/Meghan-Trainor-All-About-That-Bass-Official-Music-Video-7PCkvCPvDXk.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_1");
z.style.display = "none"
function toggle_hidden_q0_1() {
  var x = document.getElementById("answer_q0_1");
  var b = document.getElementById("button_q0_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-1, Previous question -- Q1>> +
<<s-General-Q1-10-q-3, Next question -- Q3>>

[[s-General-Q1-10-q-3]]
=== Q3

[big]#General (Q1--10): Question 3#

==== Question

Q6f184

video::LaTeX/Audio/Trimmed/American-Pie-iX-TFkut1PM.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_2" onclick="toggle_hidden_q0_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_2]]
A6f184
LaTeX/Audio/Trimmed/American-Pie-iX-TFkut1PM.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_2");
z.style.display = "none"
function toggle_hidden_q0_2() {
  var x = document.getElementById("answer_q0_2");
  var b = document.getElementById("button_q0_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-2, Previous question -- Q2>> +
<<s-General-Q1-10-q-4, Next question -- Q4>>

[[s-General-Q1-10-q-4]]
=== Q4

[big]#General (Q1--10): Question 4#

==== Question

Qef291

video::LaTeX/Audio/Trimmed/Carrie-Underwood-Before-He-Cheats-Official-Video-WaSy8yy-mr8.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_3" onclick="toggle_hidden_q0_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_3]]
Aef291
LaTeX/Audio/Trimmed/Carrie-Underwood-Before-He-Cheats-Official-Video-WaSy8yy-mr8.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_3");
z.style.display = "none"
function toggle_hidden_q0_3() {
  var x = document.getElementById("answer_q0_3");
  var b = document.getElementById("button_q0_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-3, Previous question -- Q3>> +
<<s-General-Q1-10-q-5, Next question -- Q5>>

[[s-General-Q1-10-q-5]]
=== Q5

[big]#General (Q1--10): Question 5#

==== Question

Q03cad

video::LaTeX/Audio/Trimmed/Blackbird-Remastered-2009-Man4Xw8Xypo.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_4" onclick="toggle_hidden_q0_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_4]]
A03cad
LaTeX/Audio/Trimmed/Blackbird-Remastered-2009-Man4Xw8Xypo.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_4");
z.style.display = "none"
function toggle_hidden_q0_4() {
  var x = document.getElementById("answer_q0_4");
  var b = document.getElementById("button_q0_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-4, Previous question -- Q4>> +
<<s-General-Q1-10-q-6, Next question -- Q6>>

[[s-General-Q1-10-q-6]]
=== Q6

[big]#General (Q1--10): Question 6#

==== Question

Q21845

video::LaTeX/Audio/Trimmed/Bruce-Springsteen-Born-to-Run-Official-Music-Video-IxuThNgl3YA.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_5" onclick="toggle_hidden_q0_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_5]]
A21845
LaTeX/Audio/Trimmed/Bruce-Springsteen-Born-to-Run-Official-Music-Video-IxuThNgl3YA.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_5");
z.style.display = "none"
function toggle_hidden_q0_5() {
  var x = document.getElementById("answer_q0_5");
  var b = document.getElementById("button_q0_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-5, Previous question -- Q5>> +
<<s-General-Q1-10-q-7, Next question -- Q7>>

[[s-General-Q1-10-q-7]]
=== Q7

[big]#General (Q1--10): Question 7#

==== Question

Qf428d

video::LaTeX/Audio/Trimmed/Simon-Garfunkel-Bridge-Over-Troubled-Water-Audio-4G-YQA-bsOU.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_6" onclick="toggle_hidden_q0_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_6]]
Af428d
LaTeX/Audio/Trimmed/Simon-Garfunkel-Bridge-Over-Troubled-Water-Audio-4G-YQA-bsOU.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_6");
z.style.display = "none"
function toggle_hidden_q0_6() {
  var x = document.getElementById("answer_q0_6");
  var b = document.getElementById("button_q0_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-6, Previous question -- Q6>> +
<<s-General-Q1-10-q-8, Next question -- Q8>>

[[s-General-Q1-10-q-8]]
=== Q8

[big]#General (Q1--10): Question 8#

==== Question

Q9f3c5

video::LaTeX/Audio/Trimmed/Build-Me-Up-Buttercup-Nl-2iEP1Wts.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_7" onclick="toggle_hidden_q0_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_7]]
A9f3c5
LaTeX/Audio/Trimmed/Build-Me-Up-Buttercup-Nl-2iEP1Wts.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_7");
z.style.display = "none"
function toggle_hidden_q0_7() {
  var x = document.getElementById("answer_q0_7");
  var b = document.getElementById("button_q0_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-7, Previous question -- Q7>> +
<<s-General-Q1-10-q-9, Next question -- Q9>>

[[s-General-Q1-10-q-9]]
=== Q9

[big]#General (Q1--10): Question 9#

==== Question

Qc20ab

video::LaTeX/Audio/Trimmed/Carly-Rae-Jepsen-Call-Me-Maybe-fWNaR-rxAic.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_8" onclick="toggle_hidden_q0_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_8]]
Ac20ab
LaTeX/Audio/Trimmed/Carly-Rae-Jepsen-Call-Me-Maybe-fWNaR-rxAic.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_8");
z.style.display = "none"
function toggle_hidden_q0_8() {
  var x = document.getElementById("answer_q0_8");
  var b = document.getElementById("button_q0_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-8, Previous question -- Q8>> +
<<s-General-Q1-10-q-10, Next question -- Q10>>

[[s-General-Q1-10-q-10]]
=== Q10

[big]#General (Q1--10): Question 10#

==== Question

Q9c09b

video::LaTeX/Audio/Trimmed/Eric-Clapton-Cocaine-lyrics-3bEUaeG4wH4.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q0_9" onclick="toggle_hidden_q0_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q0_9]]
A9c09b
LaTeX/Audio/Trimmed/Eric-Clapton-Cocaine-lyrics-3bEUaeG4wH4.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q0_9");
z.style.display = "none"
function toggle_hidden_q0_9() {
  var x = document.getElementById("answer_q0_9");
  var b = document.getElementById("button_q0_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-9, Previous question -- Q9>> +
<<s-General-Q11-20-q-11, Next question -- General (Q11--20): Q11>>

[[s1]]
== General (Q11--20)

[[s-General-Q11-20-q-11]]
=== Q11

[big]#General (Q11--20): Question 11#

==== Question

Qd21d6

video::LaTeX/Audio/Trimmed/Come-On-Eileen-GbpnAGajyMc.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_0" onclick="toggle_hidden_q1_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_0]]
Ad21d6
LaTeX/Audio/Trimmed/Come-On-Eileen-GbpnAGajyMc.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_0");
z.style.display = "none"
function toggle_hidden_q1_0() {
  var x = document.getElementById("answer_q1_0");
  var b = document.getElementById("button_q1_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q1-10-q-10, Previous question -- General (Q1--10): Q10>> +
<<s-General-Q11-20-q-12, Next question -- Q12>>

[[s-General-Q11-20-q-12]]
=== Q12

[big]#General (Q11--20): Question 12#

==== Question

Qe346d

video::LaTeX/Audio/Trimmed/Styx-Come-Sail-Away-Official-Video-e5MAg-yWsq8.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_1" onclick="toggle_hidden_q1_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_1]]
Ae346d
LaTeX/Audio/Trimmed/Styx-Come-Sail-Away-Official-Video-e5MAg-yWsq8.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_1");
z.style.display = "none"
function toggle_hidden_q1_1() {
  var x = document.getElementById("answer_q1_1");
  var b = document.getElementById("button_q1_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-11, Previous question -- Q11>> +
<<s-General-Q11-20-q-13, Next question -- Q13>>

[[s-General-Q11-20-q-13]]
=== Q13

[big]#General (Q11--20): Question 13#

==== Question

Qf439a

video::LaTeX/Audio/Trimmed/Gnarls-Barkley-Crazy-Official-Video-N4jf6rtyuw.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_2" onclick="toggle_hidden_q1_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_2]]
Af439a
LaTeX/Audio/Trimmed/Gnarls-Barkley-Crazy-Official-Video-N4jf6rtyuw.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_2");
z.style.display = "none"
function toggle_hidden_q1_2() {
  var x = document.getElementById("answer_q1_2");
  var b = document.getElementById("button_q1_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-12, Previous question -- Q12>> +
<<s-General-Q11-20-q-14, Next question -- Q14>>

[[s-General-Q11-20-q-14]]
=== Q14

[big]#General (Q11--20): Question 14#

==== Question

Q7e3d4

video::LaTeX/Audio/Trimmed/10.-Rupert-Holmes-Escape-The-Pi-a-Colada-Song-TazHNpt6OTo.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_3" onclick="toggle_hidden_q1_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_3]]
A7e3d4
LaTeX/Audio/Trimmed/10.-Rupert-Holmes-Escape-The-Pi-a-Colada-Song-TazHNpt6OTo.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_3");
z.style.display = "none"
function toggle_hidden_q1_3() {
  var x = document.getElementById("answer_q1_3");
  var b = document.getElementById("button_q1_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-13, Previous question -- Q13>> +
<<s-General-Q11-20-q-15, Next question -- Q15>>

[[s-General-Q11-20-q-15]]
=== Q15

[big]#General (Q11--20): Question 15#

==== Question

Q6a114

video::LaTeX/Audio/Trimmed/The-Police-Every-Breath-You-Take-OMOGaugKpzs.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_4" onclick="toggle_hidden_q1_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_4]]
A6a114
LaTeX/Audio/Trimmed/The-Police-Every-Breath-You-Take-OMOGaugKpzs.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_4");
z.style.display = "none"
function toggle_hidden_q1_4() {
  var x = document.getElementById("answer_q1_4");
  var b = document.getElementById("button_q1_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-14, Previous question -- Q14>> +
<<s-General-Q11-20-q-16, Next question -- Q16>>

[[s-General-Q11-20-q-16]]
=== Q16

[big]#General (Q11--20): Question 16#

==== Question

Q80c4a

video::LaTeX/Audio/Trimmed/Elvis-Costello-The-Attractions-Everyday-I-Write-The-Book-V1d4r9awjKE.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_5" onclick="toggle_hidden_q1_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_5]]
A80c4a
LaTeX/Audio/Trimmed/Elvis-Costello-The-Attractions-Everyday-I-Write-The-Book-V1d4r9awjKE.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_5");
z.style.display = "none"
function toggle_hidden_q1_5() {
  var x = document.getElementById("answer_q1_5");
  var b = document.getElementById("button_q1_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-15, Previous question -- Q15>> +
<<s-General-Q11-20-q-17, Next question -- Q17>>

[[s-General-Q11-20-q-17]]
=== Q17

[big]#General (Q11--20): Question 17#

==== Question

Qbcc9c

video::LaTeX/Audio/Trimmed/Jonas-Blue-ft.-Dakota-Fast-Car-Official-Music-Video-0wpuR68uw-8.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_6" onclick="toggle_hidden_q1_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_6]]
Abcc9c
LaTeX/Audio/Trimmed/Jonas-Blue-ft.-Dakota-Fast-Car-Official-Music-Video-0wpuR68uw-8.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_6");
z.style.display = "none"
function toggle_hidden_q1_6() {
  var x = document.getElementById("answer_q1_6");
  var b = document.getElementById("button_q1_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-16, Previous question -- Q16>> +
<<s-General-Q11-20-q-18, Next question -- Q18>>

[[s-General-Q11-20-q-18]]
=== Q18

[big]#General (Q11--20): Question 18#

==== Question

Qbaa2d

video::LaTeX/Audio/Trimmed/Free-Bird-CqnU-sJ8V-E.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_7" onclick="toggle_hidden_q1_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_7]]
Abaa2d
LaTeX/Audio/Trimmed/Free-Bird-CqnU-sJ8V-E.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_7");
z.style.display = "none"
function toggle_hidden_q1_7() {
  var x = document.getElementById("answer_q1_7");
  var b = document.getElementById("button_q1_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-17, Previous question -- Q17>> +
<<s-General-Q11-20-q-19, Next question -- Q19>>

[[s-General-Q11-20-q-19]]
=== Q19

[big]#General (Q11--20): Question 19#

==== Question

Qf9fa6

video::LaTeX/Audio/Trimmed/Daft-Punk-Get-Lucky-Official-Audio-ft.-Pharrell-Williams-Nile-Rodgers-5NV6Rdv1a3I.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_8" onclick="toggle_hidden_q1_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_8]]
Af9fa6
LaTeX/Audio/Trimmed/Daft-Punk-Get-Lucky-Official-Audio-ft.-Pharrell-Williams-Nile-Rodgers-5NV6Rdv1a3I.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_8");
z.style.display = "none"
function toggle_hidden_q1_8() {
  var x = document.getElementById("answer_q1_8");
  var b = document.getElementById("button_q1_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-18, Previous question -- Q18>> +
<<s-General-Q11-20-q-20, Next question -- Q20>>

[[s-General-Q11-20-q-20]]
=== Q20

[big]#General (Q11--20): Question 20#

==== Question

Qf820e

video::LaTeX/Audio/Trimmed/Cyndi-Lauper-Girls-Just-Want-To-Have-Fun-Official-Video-PIb6AZdTr-A.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q1_9" onclick="toggle_hidden_q1_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q1_9]]
Af820e
LaTeX/Audio/Trimmed/Cyndi-Lauper-Girls-Just-Want-To-Have-Fun-Official-Video-PIb6AZdTr-A.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q1_9");
z.style.display = "none"
function toggle_hidden_q1_9() {
  var x = document.getElementById("answer_q1_9");
  var b = document.getElementById("button_q1_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-19, Previous question -- Q19>> +
<<s-General-Q21-30-q-21, Next question -- General (Q21--30): Q21>>

[[s2]]
== General (Q21--30)

[[s-General-Q21-30-q-21]]
=== Q21

[big]#General (Q21--30): Question 21#

==== Question

Q2b513

video::LaTeX/Audio/Trimmed/Go-Your-Own-Way-2004-Remaster-DubafeFeJ7Y.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_0" onclick="toggle_hidden_q2_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_0]]
A2b513
LaTeX/Audio/Trimmed/Go-Your-Own-Way-2004-Remaster-DubafeFeJ7Y.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_0");
z.style.display = "none"
function toggle_hidden_q2_0() {
  var x = document.getElementById("answer_q2_0");
  var b = document.getElementById("button_q2_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q11-20-q-20, Previous question -- General (Q11--20): Q20>> +
<<s-General-Q21-30-q-22, Next question -- Q22>>

[[s-General-Q21-30-q-22]]
=== Q22

[big]#General (Q21--30): Question 22#

==== Question

Qc8d5a

video::LaTeX/Audio/Trimmed/God-Only-Knows-Remastered-CWPo5SC3zik.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_1" onclick="toggle_hidden_q2_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_1]]
Ac8d5a
LaTeX/Audio/Trimmed/God-Only-Knows-Remastered-CWPo5SC3zik.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_1");
z.style.display = "none"
function toggle_hidden_q2_1() {
  var x = document.getElementById("answer_q2_1");
  var b = document.getElementById("button_q2_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-21, Previous question -- Q21>> +
<<s-General-Q21-30-q-23, Next question -- Q23>>

[[s-General-Q21-30-q-23]]
=== Q23

[big]#General (Q21--30): Question 23#

==== Question

Qe2719

video::LaTeX/Audio/Trimmed/Kanye-West-Gold-Digger-ft.-Jamie-Foxx-6vwNcNOTVzY.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_2" onclick="toggle_hidden_q2_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_2]]
Ae2719
LaTeX/Audio/Trimmed/Kanye-West-Gold-Digger-ft.-Jamie-Foxx-6vwNcNOTVzY.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_2");
z.style.display = "none"
function toggle_hidden_q2_2() {
  var x = document.getElementById("answer_q2_2");
  var b = document.getElementById("button_q2_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-22, Previous question -- Q22>> +
<<s-General-Q21-30-q-24, Next question -- Q24>>

[[s-General-Q21-30-q-24]]
=== Q24

[big]#General (Q21--30): Question 24#

==== Question

Qd231d

video::LaTeX/Audio/Trimmed/GOOD-VIBRATIONS-HD-THE-BEACH-BOYS-mdt0SOqPJcg.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_3" onclick="toggle_hidden_q2_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_3]]
Ad231d
LaTeX/Audio/Trimmed/GOOD-VIBRATIONS-HD-THE-BEACH-BOYS-mdt0SOqPJcg.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_3");
z.style.display = "none"
function toggle_hidden_q2_3() {
  var x = document.getElementById("answer_q2_3");
  var b = document.getElementById("button_q2_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-23, Previous question -- Q23>> +
<<s-General-Q21-30-q-25, Next question -- Q25>>

[[s-General-Q21-30-q-25]]
=== Q25

[big]#General (Q21--30): Question 25#

==== Question

Q9fb7f

video::LaTeX/Audio/Trimmed/Pharrell-Williams-Happy-Official-Music-Video-ZbZSe6N-BXs.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_4" onclick="toggle_hidden_q2_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_4]]
A9fb7f
LaTeX/Audio/Trimmed/Pharrell-Williams-Happy-Official-Music-Video-ZbZSe6N-BXs.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_4");
z.style.display = "none"
function toggle_hidden_q2_4() {
  var x = document.getElementById("answer_q2_4");
  var b = document.getElementById("button_q2_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-24, Previous question -- Q24>> +
<<s-General-Q21-30-q-26, Next question -- Q26>>

[[s-General-Q21-30-q-26]]
=== Q26

[big]#General (Q21--30): Question 26#

==== Question

Qbf0f0

video::LaTeX/Audio/Trimmed/Creedence-Clearwater-Revival-Have-You-Ever-Seen-The-Rain-Gu2pVPWGYMQ.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_5" onclick="toggle_hidden_q2_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_5]]
Abf0f0
LaTeX/Audio/Trimmed/Creedence-Clearwater-Revival-Have-You-Ever-Seen-The-Rain-Gu2pVPWGYMQ.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_5");
z.style.display = "none"
function toggle_hidden_q2_5() {
  var x = document.getElementById("answer_q2_5");
  var b = document.getElementById("button_q2_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-25, Previous question -- Q25>> +
<<s-General-Q21-30-q-27, Next question -- Q27>>

[[s-General-Q21-30-q-27]]
=== Q27

[big]#General (Q21--30): Question 27#

==== Question

Q00702

video::LaTeX/Audio/Trimmed/Avicii-Hey-Brother-Lyric-YxIiPLVR6NA.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_6" onclick="toggle_hidden_q2_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_6]]
A00702
LaTeX/Audio/Trimmed/Avicii-Hey-Brother-Lyric-YxIiPLVR6NA.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_6");
z.style.display = "none"
function toggle_hidden_q2_6() {
  var x = document.getElementById("answer_q2_6");
  var b = document.getElementById("button_q2_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-26, Previous question -- Q26>> +
<<s-General-Q21-30-q-28, Next question -- Q28>>

[[s-General-Q21-30-q-28]]
=== Q28

[big]#General (Q21--30): Question 28#

==== Question

Q75644

video::LaTeX/Audio/Trimmed/Holiday-Boulevard-of-Broken-Dreams-J0xe5DcnYSA.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_7" onclick="toggle_hidden_q2_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_7]]
A75644
LaTeX/Audio/Trimmed/Holiday-Boulevard-of-Broken-Dreams-J0xe5DcnYSA.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_7");
z.style.display = "none"
function toggle_hidden_q2_7() {
  var x = document.getElementById("answer_q2_7");
  var b = document.getElementById("button_q2_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-27, Previous question -- Q27>> +
<<s-General-Q21-30-q-29, Next question -- Q29>>

[[s-General-Q21-30-q-29]]
=== Q29

[big]#General (Q21--30): Question 29#

==== Question

Q3f9d9

video::LaTeX/Audio/Trimmed/The-Black-Eyed-Peas-I-Gotta-Feeling-Official-Music-Video-uSD4vsh1zDA.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_8" onclick="toggle_hidden_q2_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_8]]
A3f9d9
LaTeX/Audio/Trimmed/The-Black-Eyed-Peas-I-Gotta-Feeling-Official-Music-Video-uSD4vsh1zDA.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_8");
z.style.display = "none"
function toggle_hidden_q2_8() {
  var x = document.getElementById("answer_q2_8");
  var b = document.getElementById("button_q2_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-28, Previous question -- Q28>> +
<<s-General-Q21-30-q-30, Next question -- Q30>>

[[s-General-Q21-30-q-30]]
=== Q30

[big]#General (Q21--30): Question 30#

==== Question

Qed31b

video::LaTeX/Audio/Trimmed/I-Want-To-Hold-Your-Hand-Remastered-2015-v1HDt1tknTc.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q2_9" onclick="toggle_hidden_q2_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q2_9]]
Aed31b
LaTeX/Audio/Trimmed/I-Want-To-Hold-Your-Hand-Remastered-2015-v1HDt1tknTc.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q2_9");
z.style.display = "none"
function toggle_hidden_q2_9() {
  var x = document.getElementById("answer_q2_9");
  var b = document.getElementById("button_q2_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-29, Previous question -- Q29>> +
<<s-General-Q31-40-q-31, Next question -- General (Q31--40): Q31>>

[[s3]]
== General (Q31--40)

[[s-General-Q31-40-q-31]]
=== Q31

[big]#General (Q31--40): Question 31#

==== Question

Q6adbf

video::LaTeX/Audio/Trimmed/GLORIA-GAYNOR-I-Will-Survive-Original-Single-Version-Vne-5xnxpRg.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_0" onclick="toggle_hidden_q3_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_0]]
A6adbf
LaTeX/Audio/Trimmed/GLORIA-GAYNOR-I-Will-Survive-Original-Single-Version-Vne-5xnxpRg.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_0");
z.style.display = "none"
function toggle_hidden_q3_0() {
  var x = document.getElementById("answer_q3_0");
  var b = document.getElementById("button_q3_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q21-30-q-30, Previous question -- General (Q21--30): Q30>> +
<<s-General-Q31-40-q-32, Next question -- Q32>>

[[s-General-Q31-40-q-32]]
=== Q32

[big]#General (Q31--40): Question 32#

==== Question

Q01741

video::LaTeX/Audio/Trimmed/Imagine-Ultimate-Mix-0DNwYnJivJw.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_1" onclick="toggle_hidden_q3_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_1]]
A01741
LaTeX/Audio/Trimmed/Imagine-Ultimate-Mix-0DNwYnJivJw.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_1");
z.style.display = "none"
function toggle_hidden_q3_1() {
  var x = document.getElementById("answer_q3_1");
  var b = document.getElementById("button_q3_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-31, Previous question -- Q31>> +
<<s-General-Q31-40-q-33, Next question -- Q33>>

[[s-General-Q31-40-q-33]]
=== Q33

[big]#General (Q31--40): Question 33#

==== Question

Qcf53d

video::LaTeX/Audio/Trimmed/JOE-JACKSON-Is-She-Really-Going-Out-with-Him-HD-6TzKSFbsh2Y.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_2" onclick="toggle_hidden_q3_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_2]]
Acf53d
LaTeX/Audio/Trimmed/JOE-JACKSON-Is-She-Really-Going-Out-with-Him-HD-6TzKSFbsh2Y.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_2");
z.style.display = "none"
function toggle_hidden_q3_2() {
  var x = document.getElementById("answer_q3_2");
  var b = document.getElementById("button_q3_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-32, Previous question -- Q32>> +
<<s-General-Q31-40-q-34, Next question -- Q34>>

[[s-General-Q31-40-q-34]]
=== Q34

[big]#General (Q31--40): Question 34#

==== Question

Q5b2a8

video::LaTeX/Audio/Trimmed/Bob-Marley-The-Wailers-Is-This-Love-cOJsK8qbAaA.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_3" onclick="toggle_hidden_q3_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_3]]
A5b2a8
LaTeX/Audio/Trimmed/Bob-Marley-The-Wailers-Is-This-Love-cOJsK8qbAaA.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_3");
z.style.display = "none"
function toggle_hidden_q3_3() {
  var x = document.getElementById("answer_q3_3");
  var b = document.getElementById("button_q3_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-33, Previous question -- Q33>> +
<<s-General-Q31-40-q-35, Next question -- Q35>>

[[s-General-Q31-40-q-35]]
=== Q35

[big]#General (Q31--40): Question 35#

==== Question

Qd1df6

video::LaTeX/Audio/Trimmed/Elvis-Presley-Jailhouse-Rock-Music-Video-gj0Rz-uP4Mk.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_4" onclick="toggle_hidden_q3_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_4]]
Ad1df6
LaTeX/Audio/Trimmed/Elvis-Presley-Jailhouse-Rock-Music-Video-gj0Rz-uP4Mk.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_4");
z.style.display = "none"
function toggle_hidden_q3_4() {
  var x = document.getElementById("answer_q3_4");
  var b = document.getElementById("button_q3_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-34, Previous question -- Q34>> +
<<s-General-Q31-40-q-36, Next question -- Q36>>

[[s-General-Q31-40-q-36]]
=== Q36

[big]#General (Q31--40): Question 36#

==== Question

Q8754e

video::LaTeX/Audio/Trimmed/Chuck-Berry-Johnny-B.-Goode-Single-tXba00vudss.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_5" onclick="toggle_hidden_q3_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_5]]
A8754e
LaTeX/Audio/Trimmed/Chuck-Berry-Johnny-B.-Goode-Single-tXba00vudss.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_5");
z.style.display = "none"
function toggle_hidden_q3_5() {
  var x = document.getElementById("answer_q3_5");
  var b = document.getElementById("button_q3_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-35, Previous question -- Q35>> +
<<s-General-Q31-40-q-37, Next question -- Q37>>

[[s-General-Q31-40-q-37]]
=== Q37

[big]#General (Q31--40): Question 37#

==== Question

Q4415c

video::LaTeX/Audio/Trimmed/Dolly-Parton-Jolene-Audio-Ixrje2rXLMA.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_6" onclick="toggle_hidden_q3_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_6]]
A4415c
LaTeX/Audio/Trimmed/Dolly-Parton-Jolene-Audio-Ixrje2rXLMA.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_6");
z.style.display = "none"
function toggle_hidden_q3_6() {
  var x = document.getElementById("answer_q3_6");
  var b = document.getElementById("button_q3_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-36, Previous question -- Q36>> +
<<s-General-Q31-40-q-38, Next question -- Q38>>

[[s-General-Q31-40-q-38]]
=== Q38

[big]#General (Q31--40): Question 38#

==== Question

Q63d6c

video::LaTeX/Audio/Trimmed/Culture-Club-Karma-Chameleon-Official-Video-JmcA9LIIXWw.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_7" onclick="toggle_hidden_q3_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_7]]
A63d6c
LaTeX/Audio/Trimmed/Culture-Club-Karma-Chameleon-Official-Video-JmcA9LIIXWw.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_7");
z.style.display = "none"
function toggle_hidden_q3_7() {
  var x = document.getElementById("answer_q3_7");
  var b = document.getElementById("button_q3_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-37, Previous question -- Q37>> +
<<s-General-Q31-40-q-39, Next question -- Q39>>

[[s-General-Q31-40-q-39]]
=== Q39

[big]#General (Q31--40): Question 39#

==== Question

Q5baac

video::LaTeX/Audio/Trimmed/-Lean-On-Me-singer-Bill-Withers-dies-at-81-DN-dvc5bBWM.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_8" onclick="toggle_hidden_q3_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_8]]
A5baac
LaTeX/Audio/Trimmed/-Lean-On-Me-singer-Bill-Withers-dies-at-81-DN-dvc5bBWM.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_8");
z.style.display = "none"
function toggle_hidden_q3_8() {
  var x = document.getElementById("answer_q3_8");
  var b = document.getElementById("button_q3_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-38, Previous question -- Q38>> +
<<s-General-Q31-40-q-40, Next question -- Q40>>

[[s-General-Q31-40-q-40]]
=== Q40

[big]#General (Q31--40): Question 40#

==== Question

Q4301b

video::LaTeX/Audio/Trimmed/The-Doors-Light-My-Fire-cq8k-ZbsXDI.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q3_9" onclick="toggle_hidden_q3_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q3_9]]
A4301b
LaTeX/Audio/Trimmed/The-Doors-Light-My-Fire-cq8k-ZbsXDI.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q3_9");
z.style.display = "none"
function toggle_hidden_q3_9() {
  var x = document.getElementById("answer_q3_9");
  var b = document.getElementById("button_q3_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-39, Previous question -- Q39>> +
<<s-General-Q41-50-q-41, Next question -- General (Q41--50): Q41>>

[[s4]]
== General (Q41--50)

[[s-General-Q41-50-q-41]]
=== Q41

[big]#General (Q41--50): Question 41#

==== Question

Q8c7cc

video::LaTeX/Audio/Trimmed/Jimmy-Buffett-Margaritaville-with-lyrics-ue2-ZVxpVjc.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_0" onclick="toggle_hidden_q4_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_0]]
A8c7cc
LaTeX/Audio/Trimmed/Jimmy-Buffett-Margaritaville-with-lyrics-ue2-ZVxpVjc.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_0");
z.style.display = "none"
function toggle_hidden_q4_0() {
  var x = document.getElementById("answer_q4_0");
  var b = document.getElementById("button_q4_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q31-40-q-40, Previous question -- General (Q31--40): Q40>> +
<<s-General-Q41-50-q-42, Next question -- Q42>>

[[s-General-Q41-50-q-42]]
=== Q42

[big]#General (Q41--50): Question 42#

==== Question

Q1cc27

video::LaTeX/Audio/Trimmed/Madonna-Material-Girl-Official-Music-Video-6p-lDYPR2P8.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_1" onclick="toggle_hidden_q4_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_1]]
A1cc27
LaTeX/Audio/Trimmed/Madonna-Material-Girl-Official-Music-Video-6p-lDYPR2P8.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_1");
z.style.display = "none"
function toggle_hidden_q4_1() {
  var x = document.getElementById("answer_q4_1");
  var b = document.getElementById("button_q4_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-41, Previous question -- Q41>> +
<<s-General-Q41-50-q-43, Next question -- Q43>>

[[s-General-Q41-50-q-43]]
=== Q43

[big]#General (Q41--50): Question 43#

==== Question

Q4f74e

video::LaTeX/Audio/Trimmed/Moondance-2013-Remaster-7kfYOGndVfU.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_2" onclick="toggle_hidden_q4_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_2]]
A4f74e
LaTeX/Audio/Trimmed/Moondance-2013-Remaster-7kfYOGndVfU.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_2");
z.style.display = "none"
function toggle_hidden_q4_2() {
  var x = document.getElementById("answer_q4_2");
  var b = document.getElementById("button_q4_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-42, Previous question -- Q42>> +
<<s-General-Q41-50-q-44, Next question -- Q44>>

[[s-General-Q41-50-q-44]]
=== Q44

[big]#General (Q41--50): Question 44#

==== Question

Q12a94

video::LaTeX/Audio/Trimmed/My-Generation-Mono-Version-fRipFYoji2A.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_3" onclick="toggle_hidden_q4_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_3]]
A12a94
LaTeX/Audio/Trimmed/My-Generation-Mono-Version-fRipFYoji2A.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_3");
z.style.display = "none"
function toggle_hidden_q4_3() {
  var x = document.getElementById("answer_q4_3");
  var b = document.getElementById("button_q4_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-43, Previous question -- Q43>> +
<<s-General-Q41-50-q-45, Next question -- Q45>>

[[s-General-Q41-50-q-45]]
=== Q45

[big]#General (Q41--50): Question 45#

==== Question

Q58829

video::LaTeX/Audio/Trimmed/Norwegian-Wood-This-Bird-Has-Flown-Y-V6y1ZCg-8.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_4" onclick="toggle_hidden_q4_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_4]]
A58829
LaTeX/Audio/Trimmed/Norwegian-Wood-This-Bird-Has-Flown-Y-V6y1ZCg-8.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_4");
z.style.display = "none"
function toggle_hidden_q4_4() {
  var x = document.getElementById("answer_q4_4");
  var b = document.getElementById("button_q4_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-44, Previous question -- Q44>> +
<<s-General-Q41-50-q-46, Next question -- Q46>>

[[s-General-Q41-50-q-46]]
=== Q46

[big]#General (Q41--50): Question 46#

==== Question

Q7f7a2

video::LaTeX/Audio/Trimmed/Lil-Nas-X-Old-Town-Road-feat.-Billy-Ray-Cyrus-Remix-7ysFgElQtjI.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_5" onclick="toggle_hidden_q4_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_5]]
A7f7a2
LaTeX/Audio/Trimmed/Lil-Nas-X-Old-Town-Road-feat.-Billy-Ray-Cyrus-Remix-7ysFgElQtjI.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_5");
z.style.display = "none"
function toggle_hidden_q4_5() {
  var x = document.getElementById("answer_q4_5");
  var b = document.getElementById("button_q4_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-45, Previous question -- Q45>> +
<<s-General-Q41-50-q-47, Next question -- Q47>>

[[s-General-Q41-50-q-47]]
=== Q47

[big]#General (Q41--50): Question 47#

==== Question

Q88b39

video::LaTeX/Audio/Trimmed/One-Way-Or-Another-Remastered-Fnb1xYDViDs.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_6" onclick="toggle_hidden_q4_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_6]]
A88b39
LaTeX/Audio/Trimmed/One-Way-Or-Another-Remastered-Fnb1xYDViDs.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_6");
z.style.display = "none"
function toggle_hidden_q4_6() {
  var x = document.getElementById("answer_q4_6");
  var b = document.getElementById("button_q4_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-46, Previous question -- Q46>> +
<<s-General-Q41-50-q-48, Next question -- Q48>>

[[s-General-Q41-50-q-48]]
=== Q48

[big]#General (Q41--50): Question 48#

==== Question

Q08c67

video::LaTeX/Audio/Trimmed/Yes-Owner-of-a-Lonely-Heart-HQ-7LLzPPFc21o.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_7" onclick="toggle_hidden_q4_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_7]]
A08c67
LaTeX/Audio/Trimmed/Yes-Owner-of-a-Lonely-Heart-HQ-7LLzPPFc21o.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_7");
z.style.display = "none"
function toggle_hidden_q4_7() {
  var x = document.getElementById("answer_q4_7");
  var b = document.getElementById("button_q4_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-47, Previous question -- Q47>> +
<<s-General-Q41-50-q-49, Next question -- Q49>>

[[s-General-Q41-50-q-49]]
=== Q49

[big]#General (Q41--50): Question 49#

==== Question

Q1c919

video::LaTeX/Audio/Trimmed/The-Rolling-Stones-Paint-It-Black-Official-Lyric-Video-O4irXQhgMqg.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_8" onclick="toggle_hidden_q4_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_8]]
A1c919
LaTeX/Audio/Trimmed/The-Rolling-Stones-Paint-It-Black-Official-Lyric-Video-O4irXQhgMqg.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_8");
z.style.display = "none"
function toggle_hidden_q4_8() {
  var x = document.getElementById("answer_q4_8");
  var b = document.getElementById("button_q4_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-48, Previous question -- Q48>> +
<<s-General-Q41-50-q-50, Next question -- Q50>>

[[s-General-Q41-50-q-50]]
=== Q50

[big]#General (Q41--50): Question 50#

==== Question

Qf04aa

video::LaTeX/Audio/Trimmed/Elvis-Costello-The-Attractions-Pump-It-Up-3Y71iDvCYXA.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q4_9" onclick="toggle_hidden_q4_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q4_9]]
Af04aa
LaTeX/Audio/Trimmed/Elvis-Costello-The-Attractions-Pump-It-Up-3Y71iDvCYXA.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q4_9");
z.style.display = "none"
function toggle_hidden_q4_9() {
  var x = document.getElementById("answer_q4_9");
  var b = document.getElementById("button_q4_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-49, Previous question -- Q49>> +
<<s-General-Q51-60-q-51, Next question -- General (Q51--60): Q51>>

[[s5]]
== General (Q51--60)

[[s-General-Q51-60-q-51]]
=== Q51

[big]#General (Q51--60): Question 51#

==== Question

Q21a35

video::LaTeX/Audio/Trimmed/Jason-Derulo-Ridin-Solo-Official-Video-in-HD-8ESdn0MuJWQ.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_0" onclick="toggle_hidden_q5_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_0]]
A21a35
LaTeX/Audio/Trimmed/Jason-Derulo-Ridin-Solo-Official-Video-in-HD-8ESdn0MuJWQ.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_0");
z.style.display = "none"
function toggle_hidden_q5_0() {
  var x = document.getElementById("answer_q5_0");
  var b = document.getElementById("button_q5_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q41-50-q-50, Previous question -- General (Q41--50): Q50>> +
<<s-General-Q51-60-q-52, Next question -- Q52>>

[[s-General-Q51-60-q-52]]
=== Q52

[big]#General (Q51--60): Question 52#

==== Question

Q55bb6

video::LaTeX/Audio/Trimmed/Ring-of-Fire-Johnny-Cash-mIBTg7q9oNc.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_1" onclick="toggle_hidden_q5_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_1]]
A55bb6
LaTeX/Audio/Trimmed/Ring-of-Fire-Johnny-Cash-mIBTg7q9oNc.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_1");
z.style.display = "none"
function toggle_hidden_q5_1() {
  var x = document.getElementById("answer_q5_1");
  var b = document.getElementById("button_q5_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-51, Previous question -- Q51>> +
<<s-General-Q51-60-q-53, Next question -- Q53>>

[[s-General-Q51-60-q-53]]
=== Q53

[big]#General (Q51--60): Question 53#

==== Question

Qcf020

video::LaTeX/Audio/Trimmed/Lorde-Royals-US-Version-nlcIKh6sBtc.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_2" onclick="toggle_hidden_q5_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_2]]
Acf020
LaTeX/Audio/Trimmed/Lorde-Royals-US-Version-nlcIKh6sBtc.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_2");
z.style.display = "none"
function toggle_hidden_q5_2() {
  var x = document.getElementById("answer_q5_2");
  var b = document.getElementById("button_q5_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-52, Previous question -- Q52>> +
<<s-General-Q51-60-q-54, Next question -- Q54>>

[[s-General-Q51-60-q-54]]
=== Q54

[big]#General (Q51--60): Question 54#

==== Question

Q07a47

video::LaTeX/Audio/Trimmed/Earth-Wind-Fire-September-Official-Music-Video-Gs069dndIYk.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_3" onclick="toggle_hidden_q5_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_3]]
A07a47
LaTeX/Audio/Trimmed/Earth-Wind-Fire-September-Official-Music-Video-Gs069dndIYk.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_3");
z.style.display = "none"
function toggle_hidden_q5_3() {
  var x = document.getElementById("answer_q5_3");
  var b = document.getElementById("button_q5_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-53, Previous question -- Q53>> +
<<s-General-Q51-60-q-55, Next question -- Q55>>

[[s-General-Q51-60-q-55]]
=== Q55

[big]#General (Q51--60): Question 55#

==== Question

Q45c77

video::LaTeX/Audio/Trimmed/The-Isley-Brothers-Shout-rWRsJ-mDU5o.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_4" onclick="toggle_hidden_q5_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_4]]
A45c77
LaTeX/Audio/Trimmed/The-Isley-Brothers-Shout-rWRsJ-mDU5o.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_4");
z.style.display = "none"
function toggle_hidden_q5_4() {
  var x = document.getElementById("answer_q5_4");
  var b = document.getElementById("button_q5_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-54, Previous question -- Q54>> +
<<s-General-Q51-60-q-56, Next question -- Q56>>

[[s-General-Q51-60-q-56]]
=== Q56

[big]#General (Q51--60): Question 56#

==== Question

Q81f7d

video::LaTeX/Audio/Trimmed/Nirvana-Smells-Like-Teen-Spirit-Official-Music-Video-hTWKbfoikeg.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_5" onclick="toggle_hidden_q5_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_5]]
A81f7d
LaTeX/Audio/Trimmed/Nirvana-Smells-Like-Teen-Spirit-Official-Music-Video-hTWKbfoikeg.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_5");
z.style.display = "none"
function toggle_hidden_q5_5() {
  var x = document.getElementById("answer_q5_5");
  var b = document.getElementById("button_q5_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-55, Previous question -- Q55>> +
<<s-General-Q51-60-q-57, Next question -- Q57>>

[[s-General-Q51-60-q-57]]
=== Q57

[big]#General (Q51--60): Question 57#

==== Question

Q26b5a

video::LaTeX/Audio/Trimmed/Kanye-West-Stronger-PsO6ZnUZI0g.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_6" onclick="toggle_hidden_q5_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_6]]
A26b5a
LaTeX/Audio/Trimmed/Kanye-West-Stronger-PsO6ZnUZI0g.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_6");
z.style.display = "none"
function toggle_hidden_q5_6() {
  var x = document.getElementById("answer_q5_6");
  var b = document.getElementById("button_q5_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-56, Previous question -- Q56>> +
<<s-General-Q51-60-q-58, Next question -- Q58>>

[[s-General-Q51-60-q-58]]
=== Q58

[big]#General (Q51--60): Question 58#

==== Question

Q45f93

video::LaTeX/Audio/Trimmed/Elvis-Presley-Suspicious-Minds-Audio-RxOBOhRECoo.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_7" onclick="toggle_hidden_q5_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_7]]
A45f93
LaTeX/Audio/Trimmed/Elvis-Presley-Suspicious-Minds-Audio-RxOBOhRECoo.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_7");
z.style.display = "none"
function toggle_hidden_q5_7() {
  var x = document.getElementById("answer_q5_7");
  var b = document.getElementById("button_q5_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-57, Previous question -- Q57>> +
<<s-General-Q51-60-q-59, Next question -- Q59>>

[[s-General-Q51-60-q-59]]
=== Q59

[big]#General (Q51--60): Question 59#

==== Question

Q3b0e7

video::LaTeX/Audio/Trimmed/Tequila-The-Champs-3H6amDbAwlY.mp4[width=300]

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_8" onclick="toggle_hidden_q5_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_8]]
A3b0e7
LaTeX/Audio/Trimmed/Tequila-The-Champs-3H6amDbAwlY.mp4


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_8");
z.style.display = "none"
function toggle_hidden_q5_8() {
  var x = document.getElementById("answer_q5_8");
  var b = document.getElementById("button_q5_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-58, Previous question -- Q58>> +
<<s-General-Q51-60-q-60, Next question -- Q60>>

[[s-General-Q51-60-q-60]]
=== Q60

[big]#General (Q51--60): Question 60#

==== Question

Q67ea2

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q5_9" onclick="toggle_hidden_q5_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q5_9]]
A67ea2
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q5_9");
z.style.display = "none"
function toggle_hidden_q5_9() {
  var x = document.getElementById("answer_q5_9");
  var b = document.getElementById("button_q5_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-59, Previous question -- Q59>> +
<<s-General-Q61-70-q-61, Next question -- General (Q61--70): Q61>>

[[s6]]
== General (Q61--70)

[[s-General-Q61-70-q-61]]
=== Q61

[big]#General (Q61--70): Question 61#

==== Question

Q4d618

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_0" onclick="toggle_hidden_q6_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_0]]
A4d618
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_0");
z.style.display = "none"
function toggle_hidden_q6_0() {
  var x = document.getElementById("answer_q6_0");
  var b = document.getElementById("button_q6_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q51-60-q-60, Previous question -- General (Q51--60): Q60>> +
<<s-General-Q61-70-q-62, Next question -- Q62>>

[[s-General-Q61-70-q-62]]
=== Q62

[big]#General (Q61--70): Question 62#

==== Question

Q2642d

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_1" onclick="toggle_hidden_q6_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_1]]
A2642d
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_1");
z.style.display = "none"
function toggle_hidden_q6_1() {
  var x = document.getElementById("answer_q6_1");
  var b = document.getElementById("button_q6_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q61-70-q-61, Previous question -- Q61>> +
<<s-General-Q61-70-q-63, Next question -- Q63>>

[[s-General-Q61-70-q-63]]
=== Q63

[big]#General (Q61--70): Question 63#

==== Question

Qb8c43

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_2" onclick="toggle_hidden_q6_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_2]]
Ab8c43
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_2");
z.style.display = "none"
function toggle_hidden_q6_2() {
  var x = document.getElementById("answer_q6_2");
  var b = document.getElementById("button_q6_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q61-70-q-62, Previous question -- Q62>> +
<<s-General-Q61-70-q-64, Next question -- Q64>>

[[s-General-Q61-70-q-64]]
=== Q64

[big]#General (Q61--70): Question 64#

==== Question

Qfd747

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_3" onclick="toggle_hidden_q6_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_3]]
Afd747
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_3");
z.style.display = "none"
function toggle_hidden_q6_3() {
  var x = document.getElementById("answer_q6_3");
  var b = document.getElementById("button_q6_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q61-70-q-63, Previous question -- Q63>> +
<<s-General-Q61-70-q-65, Next question -- Q65>>

[[s-General-Q61-70-q-65]]
=== Q65

[big]#General (Q61--70): Question 65#

==== Question

Qf9e48

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_4" onclick="toggle_hidden_q6_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_4]]
Af9e48
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_4");
z.style.display = "none"
function toggle_hidden_q6_4() {
  var x = document.getElementById("answer_q6_4");
  var b = document.getElementById("button_q6_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q61-70-q-64, Previous question -- Q64>> +
<<s-General-Q61-70-q-66, Next question -- Q66>>

[[s-General-Q61-70-q-66]]
=== Q66

[big]#General (Q61--70): Question 66#

==== Question

Q12b75

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_5" onclick="toggle_hidden_q6_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_5]]
A12b75
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_5");
z.style.display = "none"
function toggle_hidden_q6_5() {
  var x = document.getElementById("answer_q6_5");
  var b = document.getElementById("button_q6_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q61-70-q-65, Previous question -- Q65>> +
<<s-General-Q61-70-q-67, Next question -- Q67>>

[[s-General-Q61-70-q-67]]
=== Q67

[big]#General (Q61--70): Question 67#

==== Question

Q20a1a

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_6" onclick="toggle_hidden_q6_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_6]]
A20a1a
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_6");
z.style.display = "none"
function toggle_hidden_q6_6() {
  var x = document.getElementById("answer_q6_6");
  var b = document.getElementById("button_q6_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q61-70-q-66, Previous question -- Q66>> +
<<s-General-Q61-70-q-68, Next question -- Q68>>

[[s-General-Q61-70-q-68]]
=== Q68

[big]#General (Q61--70): Question 68#

==== Question

Qa4ae4

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_7" onclick="toggle_hidden_q6_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_7]]
Aa4ae4
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_7");
z.style.display = "none"
function toggle_hidden_q6_7() {
  var x = document.getElementById("answer_q6_7");
  var b = document.getElementById("button_q6_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q61-70-q-67, Previous question -- Q67>> +
<<s-General-Q61-70-q-69, Next question -- Q69>>

[[s-General-Q61-70-q-69]]
=== Q69

[big]#General (Q61--70): Question 69#

==== Question

Q3a7ee

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_8" onclick="toggle_hidden_q6_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_8]]
A3a7ee
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_8");
z.style.display = "none"
function toggle_hidden_q6_8() {
  var x = document.getElementById("answer_q6_8");
  var b = document.getElementById("button_q6_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q61-70-q-68, Previous question -- Q68>> +
<<s-General-Q61-70-q-70, Next question -- Q70>>

[[s-General-Q61-70-q-70]]
=== Q70

[big]#General (Q61--70): Question 70#

==== Question

Q1987b

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q6_9" onclick="toggle_hidden_q6_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q6_9]]
A1987b
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q6_9");
z.style.display = "none"
function toggle_hidden_q6_9() {
  var x = document.getElementById("answer_q6_9");
  var b = document.getElementById("button_q6_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q61-70-q-69, Previous question -- Q69>> +
<<s-Broadway-q-1, Next question -- Broadway: Q1>>

[[s7]]
== Broadway

[[s-Broadway-q-1]]
=== Q1

[big]#Broadway: Question 1#

==== Question

Qf7a0c

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_0" onclick="toggle_hidden_q7_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_0]]
Af7a0c
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_0");
z.style.display = "none"
function toggle_hidden_q7_0() {
  var x = document.getElementById("answer_q7_0");
  var b = document.getElementById("button_q7_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-General-Q61-70-q-70, Previous question -- General (Q61--70): Q70>> +
<<s-Broadway-q-2, Next question -- Q2>>

[[s-Broadway-q-2]]
=== Q2

[big]#Broadway: Question 2#

==== Question

Qedebc

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_1" onclick="toggle_hidden_q7_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_1]]
Aedebc
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_1");
z.style.display = "none"
function toggle_hidden_q7_1() {
  var x = document.getElementById("answer_q7_1");
  var b = document.getElementById("button_q7_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-1, Previous question -- Q1>> +
<<s-Broadway-q-3, Next question -- Q3>>

[[s-Broadway-q-3]]
=== Q3

[big]#Broadway: Question 3#

==== Question

Qa1079

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_2" onclick="toggle_hidden_q7_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_2]]
Aa1079
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_2");
z.style.display = "none"
function toggle_hidden_q7_2() {
  var x = document.getElementById("answer_q7_2");
  var b = document.getElementById("button_q7_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-2, Previous question -- Q2>> +
<<s-Broadway-q-4, Next question -- Q4>>

[[s-Broadway-q-4]]
=== Q4

[big]#Broadway: Question 4#

==== Question

Qaffeb

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_3" onclick="toggle_hidden_q7_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_3]]
Aaffeb
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_3");
z.style.display = "none"
function toggle_hidden_q7_3() {
  var x = document.getElementById("answer_q7_3");
  var b = document.getElementById("button_q7_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-3, Previous question -- Q3>> +
<<s-Broadway-q-5, Next question -- Q5>>

[[s-Broadway-q-5]]
=== Q5

[big]#Broadway: Question 5#

==== Question

Q9b69e

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_4" onclick="toggle_hidden_q7_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_4]]
A9b69e
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_4");
z.style.display = "none"
function toggle_hidden_q7_4() {
  var x = document.getElementById("answer_q7_4");
  var b = document.getElementById("button_q7_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-4, Previous question -- Q4>> +
<<s-Broadway-q-6, Next question -- Q6>>

[[s-Broadway-q-6]]
=== Q6

[big]#Broadway: Question 6#

==== Question

Qf3516

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_5" onclick="toggle_hidden_q7_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_5]]
Af3516
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_5");
z.style.display = "none"
function toggle_hidden_q7_5() {
  var x = document.getElementById("answer_q7_5");
  var b = document.getElementById("button_q7_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-5, Previous question -- Q5>> +
<<s-Broadway-q-7, Next question -- Q7>>

[[s-Broadway-q-7]]
=== Q7

[big]#Broadway: Question 7#

==== Question

Qfc2d7

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_6" onclick="toggle_hidden_q7_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_6]]
Afc2d7
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_6");
z.style.display = "none"
function toggle_hidden_q7_6() {
  var x = document.getElementById("answer_q7_6");
  var b = document.getElementById("button_q7_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-6, Previous question -- Q6>> +
<<s-Broadway-q-8, Next question -- Q8>>

[[s-Broadway-q-8]]
=== Q8

[big]#Broadway: Question 8#

==== Question

Q3ab84

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_7" onclick="toggle_hidden_q7_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_7]]
A3ab84
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_7");
z.style.display = "none"
function toggle_hidden_q7_7() {
  var x = document.getElementById("answer_q7_7");
  var b = document.getElementById("button_q7_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-7, Previous question -- Q7>> +
<<s-Broadway-q-9, Next question -- Q9>>

[[s-Broadway-q-9]]
=== Q9

[big]#Broadway: Question 9#

==== Question

Q53e73

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_8" onclick="toggle_hidden_q7_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_8]]
A53e73
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_8");
z.style.display = "none"
function toggle_hidden_q7_8() {
  var x = document.getElementById("answer_q7_8");
  var b = document.getElementById("button_q7_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-8, Previous question -- Q8>> +
<<s-Broadway-q-10, Next question -- Q10>>

[[s-Broadway-q-10]]
=== Q10

[big]#Broadway: Question 10#

==== Question

Q1a189

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q7_9" onclick="toggle_hidden_q7_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q7_9]]
A1a189
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q7_9");
z.style.display = "none"
function toggle_hidden_q7_9() {
  var x = document.getElementById("answer_q7_9");
  var b = document.getElementById("button_q7_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-9, Previous question -- Q9>> +
<<s-Bonus-q-1, Next question -- Bonus: Q1>>

[[s8]]
== Bonus

[[s-Bonus-q-1]]
=== Q1

[big]#Bonus: Question 1#

==== Question

Qb1591

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_0" onclick="toggle_hidden_q8_0()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_0]]
Ab1591
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_0");
z.style.display = "none"
function toggle_hidden_q8_0() {
  var x = document.getElementById("answer_q8_0");
  var b = document.getElementById("button_q8_0");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Broadway-q-10, Previous question -- Broadway: Q10>> +
<<s-Bonus-q-2, Next question -- Q2>>

[[s-Bonus-q-2]]
=== Q2

[big]#Bonus: Question 2#

==== Question

Q24ffa

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_1" onclick="toggle_hidden_q8_1()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_1]]
A24ffa
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_1");
z.style.display = "none"
function toggle_hidden_q8_1() {
  var x = document.getElementById("answer_q8_1");
  var b = document.getElementById("button_q8_1");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-1, Previous question -- Q1>> +
<<s-Bonus-q-3, Next question -- Q3>>

[[s-Bonus-q-3]]
=== Q3

[big]#Bonus: Question 3#

==== Question

Qa64ab

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_2" onclick="toggle_hidden_q8_2()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_2]]
Aa64ab
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_2");
z.style.display = "none"
function toggle_hidden_q8_2() {
  var x = document.getElementById("answer_q8_2");
  var b = document.getElementById("button_q8_2");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-2, Previous question -- Q2>> +
<<s-Bonus-q-4, Next question -- Q4>>

[[s-Bonus-q-4]]
=== Q4

[big]#Bonus: Question 4#

==== Question

Q34ea9

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_3" onclick="toggle_hidden_q8_3()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_3]]
A34ea9
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_3");
z.style.display = "none"
function toggle_hidden_q8_3() {
  var x = document.getElementById("answer_q8_3");
  var b = document.getElementById("button_q8_3");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-3, Previous question -- Q3>> +
<<s-Bonus-q-5, Next question -- Q5>>

[[s-Bonus-q-5]]
=== Q5

[big]#Bonus: Question 5#

==== Question

Q4d195

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_4" onclick="toggle_hidden_q8_4()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_4]]
A4d195
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_4");
z.style.display = "none"
function toggle_hidden_q8_4() {
  var x = document.getElementById("answer_q8_4");
  var b = document.getElementById("button_q8_4");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-4, Previous question -- Q4>> +
<<s-Bonus-q-6, Next question -- Q6>>

[[s-Bonus-q-6]]
=== Q6

[big]#Bonus: Question 6#

==== Question

Qf2435

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_5" onclick="toggle_hidden_q8_5()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_5]]
Af2435
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_5");
z.style.display = "none"
function toggle_hidden_q8_5() {
  var x = document.getElementById("answer_q8_5");
  var b = document.getElementById("button_q8_5");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-5, Previous question -- Q5>> +
<<s-Bonus-q-7, Next question -- Q7>>

[[s-Bonus-q-7]]
=== Q7

[big]#Bonus: Question 7#

==== Question

Q26a63

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_6" onclick="toggle_hidden_q8_6()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_6]]
A26a63
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_6");
z.style.display = "none"
function toggle_hidden_q8_6() {
  var x = document.getElementById("answer_q8_6");
  var b = document.getElementById("button_q8_6");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-6, Previous question -- Q6>> +
<<s-Bonus-q-8, Next question -- Q8>>

[[s-Bonus-q-8]]
=== Q8

[big]#Bonus: Question 8#

==== Question

Q11d39

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_7" onclick="toggle_hidden_q8_7()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_7]]
A11d39
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_7");
z.style.display = "none"
function toggle_hidden_q8_7() {
  var x = document.getElementById("answer_q8_7");
  var b = document.getElementById("button_q8_7");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-7, Previous question -- Q7>> +
<<s-Bonus-q-9, Next question -- Q9>>

[[s-Bonus-q-9]]
=== Q9

[big]#Bonus: Question 9#

==== Question

Q1bd6b

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_8" onclick="toggle_hidden_q8_8()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_8]]
A1bd6b
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_8");
z.style.display = "none"
function toggle_hidden_q8_8() {
  var x = document.getElementById("answer_q8_8");
  var b = document.getElementById("button_q8_8");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-8, Previous question -- Q8>> +
<<s-Bonus-q-10, Next question -- Q10>>

[[s-Bonus-q-10]]
=== Q10

[big]#Bonus: Question 10#

==== Question

Qd06f5

Media goes here

==== Answer


[subs=""]
+++++++++++++++++
<button id="button_q8_9" onclick="toggle_hidden_q8_9()">
Show answer
</button>
+++++++++++++++++

[[answer_q8_9]]
Ad06f5
None


[subs=""]
+++++++++++++++
<script>
var z = document.getElementById("answer_q8_9");
z.style.display = "none"
function toggle_hidden_q8_9() {
  var x = document.getElementById("answer_q8_9");
  var b = document.getElementById("button_q8_9");
  if (x.style.display === "none") {
    x.style.display = "block";
    b.innerHTML = "Hide answer";
  } else {
    x.style.display = "none";
    b.innerHTML = "Show answer";
  }
}
</script>
+++++++++++++++

[role="fullheight"]
<<s-Bonus-q-9, Previous question -- Q9>>
